// Code generated by go generate; DO NOT EDIT.
// Source: ../aht21b/main.go
// Launcher input adaptations are defined in generate.go.

// AHT21B 温湿度センサーの値をシリアルに出力する。
package main

import (
	"time"

	"github.com/sago35/tinygo-conf-2026-badge/firmware/badge"
)

func aht21b_main() {
	time.Sleep(100 * time.Millisecond) // センサーの起動待ち
	sensor := badge.NewSensor()

	for {
		if err := sensor.Read(); err != nil {
			println("aht21b read error:", err.Error())
		} else {
			// DeciCelsius / DeciRelHumidity は 1/10 単位の整数
			t := sensor.DeciCelsius()
			h := sensor.DeciRelHumidity()
			println("temp:", t/10, ".", t%10, "C  humidity:", h/10, ".", h%10, "%")
		}
		time.Sleep(time.Second)
	}
}
