// Code generated by go generate; DO NOT EDIT.
// Source: ../irlearn/capture.go

package main

import (
	"machine"
	"runtime/volatile"
	"time"

	"github.com/sago35/tinygo-conf-2026-badge/firmware/badge"
)

// 赤外線信号の生パルス記録。
//
// 受信モジュールの出力 (アイドル High、受光中 Low) の両エッジで割り込みを受け、
// 前のエッジからの経過時間 (マイクロ秒) を順に記録する。先頭は Low の期間
// (mark) から始まり、以降 space, mark, ... と交互に並ぶ。
// 最後のエッジから FrameGap 以上経ったらフレーム終了とみなす (メインループで判定)。

const (
	// MaxEdges は 1 フレームに記録できるパルス数の上限。
	// NEC は 67、AEHA (家電協) は 100 前後、長いものでも 200 あれば足りる。
	irlearn_MaxEdges = 200
	// FrameGap はこれ以上信号が来なければフレーム終了とみなす時間。
	irlearn_FrameGap = 30 * time.Millisecond
	// MinEdges はこれより短い記録はノイズとして捨てる。
	irlearn_MinEdges = 10
)

// capture は割り込みから書かれるので、カウンタは volatile にする。
var (
	irlearn_capBuf   [irlearn_MaxEdges]uint16
	irlearn_capCount volatile.Register32
	irlearn_capLast  time.Time
	irlearn_capArmed volatile.Register8 // 1 なら記録中
)

func irlearn_onIREdge(_ machine.Pin) {
	if irlearn_capArmed.Get() == 0 {
		return
	}
	now := time.Now()
	n := irlearn_capCount.Get()
	if n == 0 {
		// 最初のエッジ (立ち下がり) はフレームの開始。長さは次のエッジで決まる
		irlearn_capLast = now
		irlearn_capCount.Set(1)
		return
	}
	d := now.Sub(irlearn_capLast)
	irlearn_capLast = now
	if n-1 >= irlearn_MaxEdges {
		return
	}
	us := d.Microseconds()
	if us > 65535 {
		us = 65535
	}
	irlearn_capBuf[n-1] = uint16(us)
	irlearn_capCount.Set(n + 1)
}

// startCapture は記録を開始する (受信モジュールの割り込みを有効にする)。
func irlearn_startCapture() {
	irlearn_capCount.Set(0)
	irlearn_capArmed.Set(1)
	badge.IR_DATA.SetInterrupt(0, nil)
	badge.IR_DATA.SetInterrupt(machine.PinFalling|machine.PinRising, irlearn_onIREdge)
}

// stopCapture は記録を止める。
func irlearn_stopCapture() {
	irlearn_capArmed.Set(0)
	badge.IR_DATA.SetInterrupt(0, nil)
}

// captured は 1 フレーム分の記録が完了していればそのパルス列を返す。
// 完了していなければ nil。取り出したあとは次の記録に備えてクリアする。
func irlearn_captured() []uint16 {
	n := irlearn_capCount.Get()
	if n == 0 || time.Since(irlearn_capLast) < irlearn_FrameGap {
		return nil
	}
	// n はエッジ数、パルス数は n-1
	pulses := int(n) - 1
	if pulses > irlearn_MaxEdges {
		pulses = irlearn_MaxEdges
	}
	irlearn_capCount.Set(0)
	if pulses < irlearn_MinEdges {
		return nil
	}
	out := make([]uint16, pulses)
	copy(out, irlearn_capBuf[:pulses])
	return out
}
