// Code generated by go generate; DO NOT EDIT.
// Source: ../rhythm/song.go

package main

import "time"

// 曲は 8 分音符 (stepMs) 単位のステップの並び。テンポ 120 BPM。
const rhythm_stepMs = 250

const rhythm_stepsPerBar = 8

// レーン。画面の左から順に並ぶ。ジョイスティックの上と下は同じレーン。
const (
	rhythm_laneLeft   = iota // ジョイスティック左
	rhythm_laneUpDown        // ジョイスティック上または下
	rhythm_laneRight         // ジョイスティック右
	rhythm_laneSW2
	rhythm_laneSW1
	rhythm_laneCount
)

// メロディは 5 音 (ペンタトニック) で、c d e g a をそれぞれレーン 0..4 に割り当てる。
// 音が高いほど右のレーンになるので、鍵盤のように音の高さと位置が対応する。
const rhythm_noteNames = "cdega"

// melodyFreq はレーンごとのメロディの周波数 (C5 D5 E5 G5 A5)。
var rhythm_melodyFreq = [rhythm_laneCount]uint32{523, 587, 659, 784, 880}

// ベースの根音 (C3..A3)。F はメロディには無いがベースでは使う。
const rhythm_rootNames = "cdefga"

var rhythm_rootFreq = [...]uint32{131, 147, 165, 175, 196, 220}

// bar は 1 小節分の譜面。melody は 1 文字が 8 分音符 1 個で、
// c d e g a が音 (= ノーツ)、'.' が休符。root はその小節のベースの根音。
type rhythm_bar struct {
	melody string
	root   byte
}

var (
	rhythm_phraseA = []rhythm_bar{
		{"c.e.g.e.", 'c'},
		{"a.a.g...", 'f'},
		{"e.d.c.d.", 'c'},
		{"e...d...", 'g'},
	}
	rhythm_phraseB = []rhythm_bar{
		{"a.g.e.d.", 'f'},
		{"d.e.g.a.", 'g'},
		{"a.g.e.c.", 'a'},
		{"d...c...", 'c'},
	}
	rhythm_phraseC = []rhythm_bar{
		{"cdega.g.", 'c'},
		{"gaga.e..", 'f'},
		{"edcde.g.", 'c'},
		{"a.g.d...", 'g'},
	}
	rhythm_phraseD = []rhythm_bar{
		{"e.e.g.g.", 'c'},
		{"a.a.g...", 'f'},
		{"g.g.e.e.", 'g'},
		{"d.d.c...", 'c'},
	}
)

// song は曲全体。前奏 (ドラムのみ) のあとにフレーズを並べる。
var rhythm_song = rhythm_concat(rhythm_phraseA, rhythm_phraseB, rhythm_phraseA, rhythm_phraseB, rhythm_phraseC, rhythm_phraseD, rhythm_phraseC, rhythm_phraseD)

// introBars は前奏の小節数。ここでノーツが降り始めるまでの準備をする。
const rhythm_introBars = 2

// outroSteps は曲の最後のノーツのあと、結果画面に移るまでのステップ数。
const rhythm_outroSteps = 8

func rhythm_concat(phrases ...[]rhythm_bar) []rhythm_bar {
	var out []rhythm_bar
	for _, p := range phrases {
		out = append(out, p...)
	}
	return out
}

// step はシンセが 1 ステップの頭で鳴らす音。
type rhythm_step struct {
	melody uint32 // メロディの周波数 (0 なら鳴らさない)
	bass   uint32 // ベースの周波数 (0 なら鳴らさない)
	kick   bool
	hat    bool
}

// note は降ってくるノーツ 1 個。
type rhythm_note struct {
	t     time.Duration // 判定ラインに来る時刻 (曲の先頭から)
	lane  int
	state uint8
}

const (
	rhythm_notePending = iota
	rhythm_noteHit
	rhythm_noteMissed
)

// difficulty は難易度。EASY は小節の 1 拍目と 3 拍目のノーツだけを残す。
type rhythm_difficulty int

const (
	rhythm_easy rhythm_difficulty = iota
	rhythm_normal
)

// buildSong は曲 (シンセ用のステップ列) と、難易度に応じた譜面を作る。
// メロディはどちらの難易度でも全部鳴らす。
func rhythm_buildSong(d rhythm_difficulty) ([]rhythm_step, []rhythm_note) {
	total := (rhythm_introBars+len(rhythm_song))*rhythm_stepsPerBar + rhythm_outroSteps
	steps := make([]rhythm_step, total)
	var notes []rhythm_note
	for i := range steps {
		st := &steps[i]
		pos := i % rhythm_stepsPerBar
		bi := i/rhythm_stepsPerBar - rhythm_introBars
		st.kick = pos%4 == 0 && bi < len(rhythm_song)
		st.hat = pos%2 == 1 && bi < len(rhythm_song)
		if bi < 0 || bi >= len(rhythm_song) {
			continue
		}
		b := rhythm_song[bi]
		if pos%2 == 0 {
			st.bass = rhythm_rootFreq[rhythm_indexOf(rhythm_rootNames, b.root)]
		}
		lane := rhythm_indexOf(rhythm_noteNames, b.melody[pos])
		if lane < 0 {
			continue
		}
		st.melody = rhythm_melodyFreq[lane]
		if d == rhythm_easy && pos%4 != 0 {
			continue
		}
		notes = append(notes, rhythm_note{
			t:    time.Duration(i) * rhythm_stepMs * time.Millisecond,
			lane: lane,
		})
	}
	return steps, notes
}

// indexOf は names の中の c の位置を返す。無ければ -1。
func rhythm_indexOf(names string, c byte) int {
	for i := 0; i < len(names); i++ {
		if names[i] == c {
			return i
		}
	}
	return -1
}

// songLength は曲の長さ (最後のステップの終わり)。
func rhythm_songLength(steps []rhythm_step) time.Duration {
	return time.Duration(len(steps)) * rhythm_stepMs * time.Millisecond
}
