// Code generated by go generate; DO NOT EDIT.
// Source: ../irlearn/store.go

package main

import (
	"encoding/binary"

	"github.com/sago35/tinygo-conf-2026-badge/firmware/flashstore"
)

// 登録したリモコン信号の保存。flashstore の領域に全件をまとめて書く。
//
//	ヘッダ 8 バイト: magic "IRL1", count (uint16), 予約 (uint16)
//	エントリ: name (NameLen バイト、0 埋め)、pulses 数 (uint16)、予約 (uint16)、
//	          pulses (uint16 x MaxEdges、マイクロ秒)
// 各エントリは固定長 (entrySize) なので、index から位置が決まる。

const (
	irlearn_NameLen    = 12
	irlearn_MaxRemotes = 24
	irlearn_headerSize = 8
	irlearn_entrySize  = irlearn_NameLen + 2 + 2 + irlearn_MaxEdges*2
)

var irlearn_magic = [4]byte{'I', 'R', 'L', '1'}

// Remote は登録済みのリモコン信号 1 件。
type irlearn_Remote struct {
	Name   string
	Pulses []uint16
}

func irlearn_loadRemotes() []irlearn_Remote {
	var hdr [irlearn_headerSize]byte
	if err := flashstore.Read(0, hdr[:]); err != nil {
		println("flash read error:", err.Error())
		return nil
	}
	if [4]byte{hdr[0], hdr[1], hdr[2], hdr[3]} != irlearn_magic {
		return nil
	}
	count := int(binary.LittleEndian.Uint16(hdr[4:]))
	if count > irlearn_MaxRemotes {
		count = irlearn_MaxRemotes
	}
	remotes := make([]irlearn_Remote, 0, count)
	var e [irlearn_entrySize]byte
	for i := 0; i < count; i++ {
		if err := flashstore.Read(uint32(irlearn_headerSize+i*irlearn_entrySize), e[:]); err != nil {
			println("flash read error:", err.Error())
			break
		}
		n := int(binary.LittleEndian.Uint16(e[irlearn_NameLen:]))
		if n > irlearn_MaxEdges {
			n = irlearn_MaxEdges
		}
		pulses := make([]uint16, n)
		for k := range pulses {
			pulses[k] = binary.LittleEndian.Uint16(e[irlearn_NameLen+4+2*k:])
		}
		remotes = append(remotes, irlearn_Remote{Name: irlearn_trimName(e[:irlearn_NameLen]), Pulses: pulses})
	}
	return remotes
}

func irlearn_saveRemotes(remotes []irlearn_Remote) error {
	if len(remotes) > irlearn_MaxRemotes {
		remotes = remotes[:irlearn_MaxRemotes]
	}
	size := irlearn_headerSize + len(remotes)*irlearn_entrySize
	if err := flashstore.Erase(0, uint32(size)); err != nil {
		return err
	}
	var hdr [irlearn_headerSize]byte
	copy(hdr[:], irlearn_magic[:])
	binary.LittleEndian.PutUint16(hdr[4:], uint16(len(remotes)))
	if err := flashstore.Write(0, hdr[:]); err != nil {
		return err
	}
	var e [irlearn_entrySize]byte
	for i, r := range remotes {
		for k := range e {
			e[k] = 0
		}
		copy(e[:irlearn_NameLen], r.Name)
		n := len(r.Pulses)
		if n > irlearn_MaxEdges {
			n = irlearn_MaxEdges
		}
		binary.LittleEndian.PutUint16(e[irlearn_NameLen:], uint16(n))
		for k := 0; k < n; k++ {
			binary.LittleEndian.PutUint16(e[irlearn_NameLen+4+2*k:], r.Pulses[k])
		}
		if err := flashstore.Write(uint32(irlearn_headerSize+i*irlearn_entrySize), e[:]); err != nil {
			return err
		}
	}
	return nil
}

func irlearn_trimName(b []byte) string {
	n := 0
	for n < len(b) && b[n] != 0 {
		n++
	}
	return string(b[:n])
}
