// Code generated by go generate; DO NOT EDIT.
// Source: ../wifi-joystick/main.go
// Launcher input adaptations are defined in generate.go.

// Wi-Fi に接続して HTTP サーバーを立ち上げ、ジョイスティックの XY 位置と
// スイッチ (SW1, SW2, ジョイスティックのボタン) の状態をブラウザにリアルタイムで表示する。
//
// 起動直後 (Wi-Fi 接続前) にジョイスティックのセンター位置を実測するので、
// 起動時はスティックに触らないこと。
//
//	/       XY 平面にプロットする HTML ページ (約 66ms 間隔で /input を取得)
//	/input  {"x":-12,"y":345,"joy":false,"sw1":true,"sw2":false,"dead":true,"sat":true}
//	        x, y は -1000..1000 (中立 0)。dead, sat はデッドゾーンと飽和の有効/無効
//	/config?dead=1&sat=0  デッドゾーンと飽和の有効/無効を切り替える (ページのチェックボックス)
//
// SSID とパスワードはビルド時に ldflags で埋め込む。
//
//	make flash-wifi-joystick SSID=yourssid PASS=yourpassword
package main

import (
	"strconv"
	"sync"
	"time"

	"github.com/soypat/lneto/http/httphi"
	"github.com/soypat/lneto/http/httpraw"
	"tinygo.org/x/drivers/netdev"
	link "tinygo.org/x/espradio/netlink"

	"github.com/sago35/tinygo-conf-2026-badge/firmware/badge"
	"github.com/sago35/tinygo-conf-2026-badge/firmware/wifi"
)

const wifi_joystick_port uint16 = 80

// デッドゾーンと飽和の既定値 (badge.NewJoystick の値)。オフにするときは 0 と 1000 にする。
const (
	wifi_joystick_defaultDeadZone   = 50
	wifi_joystick_defaultSaturation = 850
)

// 入力の最新値。読み取りは 1 つの goroutine だけが行い、ハンドラは mu を取って読む。
// joy のフィールド変更も mu の中で行う。
var (
	wifi_joystick_mu                         sync.Mutex
	wifi_joystick_joy                        *badge.Joystick
	wifi_joystick_joyX, wifi_joystick_joyY   int
	wifi_joystick_joyBtn                     bool
	wifi_joystick_sw1On, wifi_joystick_sw2On bool
)

const wifi_joystick_indexHTML = `<!doctype html>
<html lang="ja"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Joystick</title>
<style>
body{font-family:sans-serif;margin:1em;background:#111;color:#eee}
canvas{background:#222;border:1px solid #555;touch-action:none}
.sw{display:inline-block;margin:.5em 1em .5em 0;padding:.4em 1em;border-radius:.4em;background:#333;color:#888}
.sw.on{background:#2a2;color:#fff}
#s{color:#888;font-size:.9em}
</style></head><body>
<h1>Joystick</h1>
<canvas id="c" width="320" height="320"></canvas>
<div>
<span id="sw1" class="sw">SW1</span><span id="sw2" class="sw">SW2</span><span id="joy" class="sw">JOY</span>
</div>
<p>
<label><input type="checkbox" id="dead" checked> dead zone</label>
<label><input type="checkbox" id="sat" checked> saturation</label>
<label><input type="checkbox" id="keep"> keep trail</label>
<button id="clear">clear</button>
</p>
<p id="v"></p><p id="s"></p>
<script>
const c=document.getElementById('c'),g=c.getContext('2d'),W=c.width,H=c.height;
const trail=[];const MAXTRAIL=60;
const px=v=>W/2+v*(W/2-8)/1000, py=v=>H/2-v*(H/2-8)/1000;
// keep trail: 消えない軌跡は別レイヤーに描き足していき、毎フレームまとめて合成する
const keep=document.getElementById('keep');
const layer=document.createElement('canvas');layer.width=W;layer.height=H;
const lg=layer.getContext('2d');
function addKeep(x,y){
  if(!keep.checked)return;
  lg.fillStyle='rgba(255,200,80,0.5)';lg.beginPath();lg.arc(px(x),py(y),2,0,Math.PI*2);lg.fill();
}
document.getElementById('clear').onclick=()=>{lg.clearRect(0,0,W,H);trail.length=0;};
function draw(x,y){
  g.clearRect(0,0,W,H);
  g.strokeStyle='#444';g.lineWidth=1;
  g.beginPath();g.moveTo(W/2,0);g.lineTo(W/2,H);g.moveTo(0,H/2);g.lineTo(W,H/2);g.stroke();
  g.beginPath();g.arc(W/2,H/2,W/2-2,0,Math.PI*2);g.stroke();
  g.drawImage(layer,0,0);
  for(let i=0;i<trail.length;i++){
    const a=(i+1)/trail.length;g.fillStyle='rgba(80,160,255,'+(a*0.6)+')';
    g.beginPath();g.arc(px(trail[i][0]),py(trail[i][1]),3,0,Math.PI*2);g.fill();
  }
  g.fillStyle='#4af';g.beginPath();g.arc(px(x),py(y),8,0,Math.PI*2);g.fill();
}
function setSw(id,on){document.getElementById(id).className='sw'+(on?' on':'');}
const dead=document.getElementById('dead'),sat=document.getElementById('sat');
let synced=false; // 最初の /input 応答で基板側の設定をチェックボックスに反映する
async function sendConfig(){
  try{await fetch('/config?dead='+(dead.checked?1:0)+'&sat='+(sat.checked?1:0));}
  catch(e){document.getElementById('s').textContent='config error: '+e;}
}
dead.onchange=sendConfig;sat.onchange=sendConfig;
const INTERVAL=66; // ms。応答を待ってから次を出すので、遅延時に要求が溜まらない
let fails=0;
async function update(){
  const t0=performance.now();
  try{
    const r=await fetch('/input');const j=await r.json();
    if(!synced){dead.checked=j.dead;sat.checked=j.sat;synced=true;}
    trail.push([j.x,j.y]);if(trail.length>MAXTRAIL)trail.shift();
    addKeep(j.x,j.y);
    draw(j.x,j.y);
    setSw('sw1',j.sw1);setSw('sw2',j.sw2);setSw('joy',j.joy);
    document.getElementById('v').textContent='x='+j.x+' y='+j.y+'  ('+Math.round(performance.now()-t0)+'ms)';
    document.getElementById('s').textContent='';fails=0;
  }catch(e){fails++;document.getElementById('s').textContent='error ('+fails+'): '+e;}
  setTimeout(update,Math.max(0,INTERVAL-(performance.now()-t0)));
}
draw(0,0);update();
</script></body></html>`

func wifi_joystick_main() {
	time.Sleep(2 * time.Second)
	if ssid == "" {
		wifi_joystick_failure("ssid is empty: build with -ldflags=\"-X main.ssid=... -X main.password=...\"")
	}

	sw1, sw2 := badge.NewButtons()
	wifi_joystick_joy = badge.NewJoystick()
	println("calibrating joystick center (do not touch)...")
	wifi_joystick_joy.Calibrate(500 * time.Millisecond)
	println("center:", wifi_joystick_joy.CenterX, wifi_joystick_joy.CenterY)
	go func() {
		for {
			wifi_joystick_mu.Lock()
			x, y, btn := wifi_joystick_joy.Read()
			p1, p2 := sw1.Pressed(), sw2.Pressed()
			wifi_joystick_joyX, wifi_joystick_joyY, wifi_joystick_joyBtn = x, y, btn
			wifi_joystick_sw1On, wifi_joystick_sw2On = p1, p2
			wifi_joystick_mu.Unlock()
			time.Sleep(10 * time.Millisecond)
		}
	}()

	// 接続に失敗した場合はリセットして最初からやり直す (成功するまで戻らない)
	link := &link.Esplink{}
	netdev.UseNetdev(link)
	wifi.Connect(link, ssid, password)

	var mux httphi.MuxSlice
	mux.Handle("/", wifi_joystick_index)
	mux.Handle("/input", wifi_joystick_input)
	mux.Handle("/config", wifi_joystick_config)

	var router httphi.Router
	cfg := httphi.DefaultRouterConfig(4, 2048, mux.MaxPathValues())
	wifi_joystick_failIfErr("router configure", router.Configure(&mux, cfg))
	defer router.Shutdown()

	addr, err := link.Addr()
	wifi_joystick_failIfErr("link.Addr", err)
	print("HTTP server listening on http://", addr.String(), ":", wifi_joystick_port, "\n")
	wifi_joystick_failIfErr("ListenAndServe", link.ListenAndServe(&router, wifi_joystick_port))
}

func wifi_joystick_index(exch *httphi.Exchange) {
	exch.RespondString(httphi.StatusOK, "text/html; charset=utf-8", wifi_joystick_indexHTML)
}

// レスポンス組み立て用の固定バッファ。ハンドラごとに確保しない。
var (
	wifi_joystick_bufMu sync.Mutex
	wifi_joystick_buf   [96]byte
)

func wifi_joystick_input(exch *httphi.Exchange) {
	wifi_joystick_mu.Lock()
	x, y, btn, p1, p2 := wifi_joystick_joyX, wifi_joystick_joyY, wifi_joystick_joyBtn, wifi_joystick_sw1On, wifi_joystick_sw2On
	dead, sat := wifi_joystick_joy.DeadZone > 0, wifi_joystick_joy.Saturation < 1000
	wifi_joystick_mu.Unlock()

	wifi_joystick_bufMu.Lock()
	defer wifi_joystick_bufMu.Unlock()
	b := append(wifi_joystick_buf[:0], `{"x":`...)
	b = strconv.AppendInt(b, int64(x), 10)
	b = append(b, `,"y":`...)
	b = strconv.AppendInt(b, int64(y), 10)
	b = append(b, `,"joy":`...)
	b = strconv.AppendBool(b, btn)
	b = append(b, `,"sw1":`...)
	b = strconv.AppendBool(b, p1)
	b = append(b, `,"sw2":`...)
	b = strconv.AppendBool(b, p2)
	b = append(b, `,"dead":`...)
	b = strconv.AppendBool(b, dead)
	b = append(b, `,"sat":`...)
	b = strconv.AppendBool(b, sat)
	b = append(b, '}')
	exch.Respond(httphi.StatusOK, "application/json", b)
}

var wifi_joystick_formBuf [64]byte

// config は /config?dead=1&sat=0 を受けてデッドゾーンと飽和の有効/無効を切り替える。
func wifi_joystick_config(exch *httphi.Exchange) {
	wifi_joystick_bufMu.Lock()
	defer wifi_joystick_bufMu.Unlock()
	var form httpraw.Form
	form.Reset(wifi_joystick_formBuf[:], 2)
	if err := exch.RequestParseForm(&form, true, true); err != nil {
		exch.RespondString(httphi.StatusBadRequest, "text/plain", "bad query\n")
		return
	}
	wifi_joystick_mu.Lock()
	if v := form.Get("dead"); len(v) > 0 {
		if v[0] == '1' {
			wifi_joystick_joy.DeadZone = wifi_joystick_defaultDeadZone
		} else {
			wifi_joystick_joy.DeadZone = 0
		}
	}
	if v := form.Get("sat"); len(v) > 0 {
		if v[0] == '1' {
			wifi_joystick_joy.Saturation = wifi_joystick_defaultSaturation
		} else {
			wifi_joystick_joy.Saturation = 1000
		}
	}
	dead, sat := wifi_joystick_joy.DeadZone, wifi_joystick_joy.Saturation
	wifi_joystick_mu.Unlock()
	println("config: deadzone", dead, "saturation", sat)

	b := append(wifi_joystick_buf[:0], `{"deadzone":`...)
	b = strconv.AppendInt(b, int64(dead), 10)
	b = append(b, `,"saturation":`...)
	b = strconv.AppendInt(b, int64(sat), 10)
	b = append(b, '}')
	exch.Respond(httphi.StatusOK, "application/json", b)
}

func wifi_joystick_failIfErr(action string, err error) {
	for err != nil {
		println("fail", action+":", err.Error())
		time.Sleep(time.Second)
	}
}

func wifi_joystick_failure(msg string) {
	for {
		println("failure:", msg)
		time.Sleep(time.Second)
	}
}
