// Code generated by go generate; DO NOT EDIT.
// Source: ../rhythm/main.go
// Launcher input adaptations are defined in generate.go.

// 音ゲー。上から降ってくるノーツが判定ラインに重なるタイミングで、
// 対応するボタンを押す。
//
//	レーン (左から)  L    D/U    R    2    1
//	              JOY押 ↓か↑   →   SW2  SW1
//
// ジョイスティックの上と下は同じレーン (どちらに倒してもよい)。
// メロディの音の高さ (ド レ ミ ソ ラ) とレーンが対応しているので、
// 曲を聞いていると次に来るレーンが分かる。
//
//   - タイトル画面で SW1 を押すと EASY、SW2 を押すと NORMAL で始まる
//   - 判定は PERFECT (±50ms)、GOOD (±110ms)、それより遅れると MISS。
//     ジョイスティックのレーンは倒すのに時間がかかるので、それぞれ 30ms 広い
//   - ヒットすると LED がレーンの色に光る
//   - GOOD 以上が続く (コンボ) と、コンボ数に応じて画面の演出が増える (effects.go)
//   - 曲が終わると結果 (判定ごとの数、最大コンボ、ランク) を表示する
//
// 起動直後にジョイスティックのセンター位置を測るので、そのあいだは触らないこと。
//
// 音は I2S のリングバッファに空きができるたびに audioLoop (goroutine) が補充し、
// メインループは描画の合間に処理を譲る (Framebuffer.Display と time.Sleep)。
// ゲームの時刻はスピーカーから音が出ている位置 (synth.clock) に合わせているので、
// 描画が遅れても曲と譜面はずれない。
// 入力は pollLoop (goroutine) が 2ms ごとに読んで押した時刻を記録する。
// 描画のフレーム (33ms) 単位で読むと判定が最大 1 フレーム遅れるため。
package main

import (
	"image/color"
	"time"

	"tinygo.org/x/tinyfont"
	"tinygo.org/x/tinyfont/freesans"

	"github.com/sago35/tinygo-conf-2026-badge/firmware/badge"
	"github.com/sago35/tinygo-conf-2026-badge/firmware/i2s"
	"github.com/sago35/tinygo-conf-2026-badge/firmware/ws2812s3"
)

var (
	rhythm_black    = color.RGBA{0, 0, 0, 255}
	rhythm_white    = color.RGBA{255, 255, 255, 255}
	rhythm_gray     = color.RGBA{48, 48, 48, 255}
	rhythm_darkGray = color.RGBA{24, 24, 24, 255}
	rhythm_red      = color.RGBA{255, 40, 40, 255}
	rhythm_yellow   = color.RGBA{255, 220, 0, 255}
	rhythm_cyan     = color.RGBA{0, 255, 255, 255}
	rhythm_green    = color.RGBA{0, 255, 0, 255}
)

// レーンの色と、画面下に出すラベル。
var rhythm_laneColors = [rhythm_laneCount]color.RGBA{
	{255, 64, 160, 255},  // ←
	{64, 160, 255, 255},  // ↓↑
	{255, 160, 32, 255},  // →
	{200, 120, 255, 255}, // SW2
	{255, 255, 64, 255},  // SW1
}

var rhythm_laneLabels = [rhythm_laneCount]string{"JOY", "D/U", "R", "2", "1"}

var (
	rhythm_font      = &freesans.Regular9pt7b
	rhythm_fontBold  = &freesans.Bold12pt7b
	rhythm_fontLarge = &freesans.Bold18pt7b
)

// 画面のレイアウト。
const (
	rhythm_laneW     = badge.LCD_WIDTH / rhythm_laneCount // 48
	rhythm_judgeY    = 200                                // 判定ラインの y
	rhythm_noteH     = 10
	rhythm_topMargin = 24 // スコア表示の下からノーツが現れる
)

// 判定の幅。
const (
	rhythm_perfectWindow = 50 * time.Millisecond
	rhythm_goodWindow    = 110 * time.Millisecond
)

// fallTime はノーツが画面上端から判定ラインまで落ちてくる時間 (難易度別)。
var rhythm_fallTime = [...]time.Duration{rhythm_easy: 1600 * time.Millisecond, rhythm_normal: 1200 * time.Millisecond}

// ジョイスティックを倒したとみなす量 (-1000..1000 のうち)。
// 浅めにして、倒し始めてから判定されるまでの遅れを小さくしている。
// 戻すときは joyRelease を下回ったら離したとみなす (境目でのばたつき防止)。
const (
	rhythm_joyPress   = 300
	rhythm_joyRelease = 250
)

// ジョイスティックのレーンは、倒すのにボタンより時間がかかるぶん判定の幅を広げる。
const rhythm_joyWindowBonus = 30 * time.Millisecond

// joyLatency はジョイスティックの押下時刻から差し引く遅れ。結果を出すときに
// シリアルに出る「timing」の stick と button の差を見て調整する (正なら遅れ)。
const rhythm_joyLatency = 0 * time.Millisecond

// 判定の種類。表示とカウントに使う。
const (
	rhythm_judgeNone = iota
	rhythm_judgePerfect
	rhythm_judgeGood
	rhythm_judgeMiss
)

var rhythm_judgeText = [...]string{"", "PERFECT", "GOOD", "MISS"}
var rhythm_judgeColor = [...]color.RGBA{rhythm_black, rhythm_cyan, rhythm_green, rhythm_red}

// screen は描画先のフレームバッファ。
var rhythm_screen *badge.Framebuffer

type rhythm_game struct {
	leds rhythm_ledFlash
	syn  *rhythm_synth
	joy  *badge.Joystick
	sw1  badge.Button
	sw2  badge.Button

	audio bool // 音が出せるか (I2S の初期化に成功したか)

	// pollLoop が更新する入力の状態
	held   [rhythm_laneCount]bool // 押している間 true
	events []rhythm_press         // 押した瞬間の記録 (メインループが takeEvents で取り出す)

	best [2]int // 難易度ごとの最高スコア (電源を切ると消える)
}

func rhythm_main() {
	// ジョイスティックのセンター位置は起動直後に測る (触らないこと)
	joy := badge.NewJoystick()
	joy.Calibrate(300 * time.Millisecond)

	rhythm_screen = badge.NewFramebuffer(badge.NewDisplay())
	g := &rhythm_game{
		syn:  rhythm_newSynth(),
		joy:  joy,
		leds: rhythm_newLEDFlash(),
	}
	g.sw1, g.sw2 = badge.NewButtons()

	dev := i2s.New()
	err := dev.Configure(i2s.Config{
		BCLK:         badge.I2S_BCLK,
		LRC:          badge.I2S_LRC,
		DIN:          badge.I2S_DIN,
		SampleRate:   rhythm_sampleRate,
		BufferFrames: rhythm_bufFrames,
		BufferCount:  rhythm_bufCount,
	})
	if err != nil {
		println("audio init:", err.Error())
	} else {
		g.audio = true
		go rhythm_audioLoop(dev, g.syn)
	}
	g.events = make([]rhythm_press, 0, rhythm_maxEvents)
	go g.pollLoop()

	for {
		d := g.title()
		g.result(d, g.play(d))
	}
}

// input は 6 レーンの押下状態を返す。
func (g *rhythm_game) input() (pressed [rhythm_laneCount]bool) {
	x, y, btn := g.joy.Read()
	pressed[rhythm_laneLeft] = btn
	pressed[rhythm_laneUpDown] = rhythm_tilted(y, g.held[rhythm_laneUpDown]) || rhythm_tilted(-y, g.held[rhythm_laneUpDown])
	pressed[rhythm_laneRight] = rhythm_tilted(x, g.held[rhythm_laneRight])
	pressed[rhythm_laneSW1] = g.sw1.Pressed()
	pressed[rhythm_laneSW2] = g.sw2.Pressed()
	return pressed
}

// tilted は軸の値 v が倒した状態か返す。held (直前に倒していた) ならしきい値を下げる。
func rhythm_tilted(v int, held bool) bool {
	if held {
		return v > rhythm_joyRelease
	}
	return v > rhythm_joyPress
}

// isStick はジョイスティックのレーンなら true。
func rhythm_isStick(lane int) bool {
	return lane == rhythm_laneUpDown || lane == rhythm_laneRight
}

// press はレーンを押した瞬間の記録。
type rhythm_press struct {
	lane int
	at   time.Time
}

const rhythm_maxEvents = 32

// pollLoop は 2ms ごとに入力を読み、押した瞬間をその時刻とともに記録する。
func (g *rhythm_game) pollLoop() {
	for {
		p := g.input()
		now := time.Now()
		for i := range p {
			if p[i] && !g.held[i] && len(g.events) < rhythm_maxEvents {
				g.events = append(g.events, rhythm_press{lane: i, at: now})
			}
		}
		g.held = p
		time.Sleep(2 * time.Millisecond)
	}
}

// takeEvents は記録された押下を dst にコピーして返し、記録を空にする。
func (g *rhythm_game) takeEvents(dst []rhythm_press) []rhythm_press {
	dst = append(dst[:0], g.events...)
	g.events = g.events[:0]
	return dst
}

// pressed は記録された押下の中に lane があれば true (タイトルと結果画面用)。
func rhythm_pressed(evs []rhythm_press, lane int) bool {
	for _, e := range evs {
		if e.lane == lane {
			return true
		}
	}
	return false
}

// frame は約 30fps になるように待つ。待つあいだは audioLoop が動く。
func rhythm_frame(start time.Time) {
	if d := 33*time.Millisecond - time.Since(start); d > 0 {
		time.Sleep(d)
	} else {
		time.Sleep(time.Millisecond)
	}
}

// ---- タイトル ----

func (g *rhythm_game) title() rhythm_difficulty {
	var evs []rhythm_press
	g.takeEvents(nil) // 前の画面で押したぶんは捨てる
	for {
		start := time.Now()
		evs = g.takeEvents(evs)
		if rhythm_pressed(evs, rhythm_laneSW1) {
			g.syn.beep(1047)
			return rhythm_easy
		}
		if rhythm_pressed(evs, rhythm_laneSW2) {
			g.syn.beep(1319)
			return rhythm_normal
		}

		fb := rhythm_screen
		fb.FillScreen(rhythm_black)
		rhythm_centerText(rhythm_fontLarge, 60, "TinyGo", rhythm_white)
		rhythm_centerText(rhythm_fontLarge, 96, "BEAT", rhythm_yellow)
		// レーンの色見本
		for i := 0; i < rhythm_laneCount; i++ {
			x := int16(i*rhythm_laneW) + 4
			fb.FillRectangle(x, 116, rhythm_laneW-8, rhythm_noteH, rhythm_laneColors[i])
			rhythm_centerTextAt(rhythm_font, int16(i*rhythm_laneW), rhythm_laneW, 144, rhythm_laneLabels[i], rhythm_laneColors[i])
		}
		rhythm_centerText(rhythm_font, 180, "SW1: EASY   best "+rhythm_itoa(g.best[rhythm_easy]), rhythm_white)
		rhythm_centerText(rhythm_font, 204, "SW2: NORMAL best "+rhythm_itoa(g.best[rhythm_normal]), rhythm_white)
		rhythm_centerText(rhythm_font, 230, "#"+badge.SerialNumber(), rhythm_gray)
		fb.Display()
		g.leds.update()
		rhythm_frame(start)
	}
}

// ---- プレイ ----

type rhythm_stats struct {
	counts    [4]int // judgePerfect, judgeGood, judgeMiss
	total     int
	score     int
	combo     int
	maxCombo  int
	lastJudge int
	judgeAt   time.Duration

	// ヒットのずれ (押した時刻 - ノーツの時刻) の合計と数。
	// [0] がジョイスティック、[1] がボタン。調整用にシリアルへ出す。
	offsetSum [2]time.Duration
	offsetN   [2]int
}

// timing はヒットしたときのずれを記録する。
func (s *rhythm_stats) timing(lane int, dt time.Duration) {
	k := 1
	if rhythm_isStick(lane) {
		k = 0
	}
	s.offsetSum[k] += dt
	s.offsetN[k]++
}

// avgOffsetMs はずれの平均 (ms)。正なら遅れ、負なら早い。
func (s *rhythm_stats) avgOffsetMs(k int) int {
	if s.offsetN[k] == 0 {
		return 0
	}
	return int(s.offsetSum[k] / time.Duration(s.offsetN[k]) / time.Millisecond)
}

func (s *rhythm_stats) add(j int, at time.Duration) {
	s.counts[j]++
	s.lastJudge = j
	s.judgeAt = at
	switch j {
	case rhythm_judgePerfect:
		s.combo++
		s.score += 100 + s.combo
	case rhythm_judgeGood:
		s.combo++
		s.score += 50 + s.combo/2
	case rhythm_judgeMiss:
		s.combo = 0
	}
	if s.combo > s.maxCombo {
		s.maxCombo = s.combo
	}
}

func (g *rhythm_game) play(d rhythm_difficulty) rhythm_stats {
	steps, notes := rhythm_buildSong(d)
	end := rhythm_songLength(steps)
	fall := rhythm_fallTime[d]
	st := rhythm_stats{total: len(notes)}
	var flashAt [rhythm_laneCount]time.Duration // レーンごとのヒットの時刻 (エフェクト用)
	for i := range flashAt {
		flashAt[i] = -time.Hour
	}

	if g.audio {
		g.syn.start(steps)
		for !g.syn.started() {
			time.Sleep(time.Millisecond) // audioLoop が開始時刻を決めるのを待つ
		}
	} else {
		g.syn.startSilent() // 音が出ない場合も時刻だけは進める
	}
	fx := rhythm_newEffects()
	var evs []rhythm_press
	g.takeEvents(nil)
	head := 0 // これより前のノーツは判定済み

	for {
		start := time.Now()
		now := g.syn.clock()
		if now > end {
			break
		}
		evs = g.takeEvents(evs)

		// 押したレーンで、判定の幅に入っている一番早いノーツを取る。
		// 判定には押した瞬間の時刻を使う
		for _, ev := range evs {
			lane := ev.lane
			at := g.syn.at(ev.at)
			good, perfect := rhythm_goodWindow, rhythm_perfectWindow
			if rhythm_isStick(lane) {
				at -= rhythm_joyLatency
				good += rhythm_joyWindowBonus
				perfect += rhythm_joyWindowBonus
			}
			for i := head; i < len(notes) && notes[i].t <= at+good; i++ {
				n := &notes[i]
				if n.lane != lane || n.state != rhythm_notePending {
					continue
				}
				dt := at - n.t
				signed := dt
				if dt < 0 {
					dt = -dt
				}
				if dt > good {
					continue
				}
				n.state = rhythm_noteHit
				st.timing(lane, signed)
				j := rhythm_judgeGood
				if dt <= perfect {
					j = rhythm_judgePerfect
				}
				st.add(j, now)
				fx.hit(lane, st.combo, now)
				flashAt[lane] = now
				g.leds.flash(rhythm_laneColors[lane])
				break
			}
		}

		// 判定ラインを過ぎたノーツは MISS
		for i := head; i < len(notes) && notes[i].t < now-rhythm_goodWindow; i++ {
			if notes[i].state == rhythm_notePending {
				notes[i].state = rhythm_noteMissed
				prev := st.combo
				st.add(rhythm_judgeMiss, now)
				fx.miss(prev, now)
			}
		}
		for head < len(notes) && notes[head].state != rhythm_notePending {
			head++
		}

		fx.update()
		g.drawPlay(notes, head, now, fall, g.held, flashAt, &st, fx)
		g.leds.update()
		rhythm_frame(start)
	}
	g.syn.stop()
	if st.score > g.best[d] {
		g.best[d] = st.score
	}
	return st
}

func (g *rhythm_game) drawPlay(notes []rhythm_note, head int, now, fall time.Duration, held [rhythm_laneCount]bool, flashAt [rhythm_laneCount]time.Duration, st *rhythm_stats, fx *rhythm_effects) {
	fb := rhythm_screen
	fb.FillScreen(rhythm_black)
	fx.drawBack(fb, now, st.combo)

	// レーンの背景。押しているレーンは明るく、ヒット直後はレーンの色で光らせる
	for i := 0; i < rhythm_laneCount; i++ {
		x := int16(i * rhythm_laneW)
		if held[i] {
			fb.FillRectangle(x, rhythm_topMargin, rhythm_laneW, rhythm_judgeY-rhythm_topMargin, rhythm_darkGray)
		}
		if now-flashAt[i] < 120*time.Millisecond {
			fb.FillRectangle(x, rhythm_judgeY-30, rhythm_laneW, 30, rhythm_dim(rhythm_laneColors[i]))
		}
		fb.FillRectangle(x, rhythm_topMargin, 1, badge.LCD_HEIGHT-rhythm_topMargin, rhythm_gray)
	}
	fx.judgeLine(fb, now, st.combo)

	// ノーツ。判定ラインに来る時刻から位置を決める
	for i := head; i < len(notes) && notes[i].t < now+fall; i++ {
		n := notes[i]
		if n.state != rhythm_notePending {
			continue
		}
		y := rhythm_judgeY - int16(int64(n.t-now)*int64(rhythm_judgeY-rhythm_topMargin)/int64(fall)) - rhythm_noteH/2
		if y+rhythm_noteH < rhythm_topMargin {
			continue
		}
		fb.FillRectangle(int16(n.lane*rhythm_laneW)+3, y, rhythm_laneW-6, rhythm_noteH, rhythm_laneColors[n.lane])
	}
	fx.drawFront(fb, now, st.combo)

	// レーンのラベル
	for i := 0; i < rhythm_laneCount; i++ {
		c := rhythm_laneColors[i]
		if !held[i] {
			c = rhythm_dim(c)
		}
		rhythm_centerTextAt(rhythm_font, int16(i*rhythm_laneW), rhythm_laneW, 226, rhythm_laneLabels[i], c)
	}

	// スコアとコンボ
	fb.FillRectangle(0, 0, badge.LCD_WIDTH, rhythm_topMargin, rhythm_black)
	tinyfont.WriteLine(fb, rhythm_font, 4, 18, rhythm_itoa(st.score), rhythm_white)
	if st.combo >= 2 {
		s := rhythm_itoa(st.combo) + " combo"
		_, w := tinyfont.LineWidth(rhythm_font, s)
		c := rhythm_yellow
		if st.combo >= rhythm_comboTier2 {
			c = rhythm_hue(int(now/time.Millisecond) % 1536)
		}
		tinyfont.WriteLine(fb, rhythm_font, badge.LCD_WIDTH-4-int16(w), 18, s, c)
	}
	if len(notes) > 0 && now < notes[0].t-fall {
		// 前奏のあいだ (最初のノーツが見えるまで) は案内を出す
		rhythm_centerText(rhythm_fontBold, 110, "READY", rhythm_white)
	}

	// 判定の表示 (0.4 秒)
	if st.lastJudge != rhythm_judgeNone && now-st.judgeAt < 400*time.Millisecond {
		rhythm_centerText(rhythm_fontBold, 120, rhythm_judgeText[st.lastJudge], rhythm_judgeColor[st.lastJudge])
	}
	fb.Display()
}

// ---- 結果 ----

func (g *rhythm_game) result(d rhythm_difficulty, st rhythm_stats) {
	rate := 0
	if st.total > 0 {
		rate = (st.counts[rhythm_judgePerfect]*100 + st.counts[rhythm_judgeGood]*50) / st.total
	}
	rank, rankColor := "C", rhythm_white
	switch {
	case rate >= 95:
		rank, rankColor = "S", rhythm_yellow
	case rate >= 85:
		rank, rankColor = "A", rhythm_cyan
	case rate >= 70:
		rank, rankColor = "B", rhythm_green
	}
	fc := st.counts[rhythm_judgeMiss] == 0
	println("result:", []string{"EASY", "NORMAL"}[d], "score", st.score,
		"perfect", st.counts[rhythm_judgePerfect], "good", st.counts[rhythm_judgeGood], "miss", st.counts[rhythm_judgeMiss],
		"maxcombo", st.maxCombo, "rate", rate, "rank", rank)
	println("timing (ms, + is late): stick", st.avgOffsetMs(0), "n", st.offsetN[0],
		"button", st.avgOffsetMs(1), "n", st.offsetN[1])

	shown := time.Now()
	var evs []rhythm_press
	for {
		start := time.Now()
		evs = g.takeEvents(evs)
		// 押しっぱなしのまま次に進まないよう、少し待ってから受け付ける
		if time.Since(shown) > time.Second && (rhythm_pressed(evs, rhythm_laneSW1) || rhythm_pressed(evs, rhythm_laneSW2)) {
			g.syn.beep(1047)
			return
		}

		fb := rhythm_screen
		fb.FillScreen(rhythm_black)
		rhythm_centerText(rhythm_fontBold, 28, "RESULT", rhythm_white)
		rhythm_centerText(rhythm_fontLarge, 80, rank, rankColor)
		y := int16(112)
		row := func(label string, v int, c color.RGBA) {
			tinyfont.WriteLine(fb, rhythm_font, 40, y, label, c)
			s := rhythm_itoa(v)
			_, w := tinyfont.LineWidth(rhythm_font, s)
			tinyfont.WriteLine(fb, rhythm_font, 200-int16(w), y, s, c)
			y += 20
		}
		row("PERFECT", st.counts[rhythm_judgePerfect], rhythm_cyan)
		row("GOOD", st.counts[rhythm_judgeGood], rhythm_green)
		row("MISS", st.counts[rhythm_judgeMiss], rhythm_red)
		row("MAX COMBO", st.maxCombo, rhythm_yellow)
		row("SCORE", st.score, rhythm_white)
		if fc {
			rhythm_centerText(rhythm_fontBold, 232, "FULL COMBO!", rhythm_yellow)
		} else {
			rhythm_centerText(rhythm_font, 230, "SW1/SW2: title", rhythm_gray)
		}
		fb.Display()
		g.leds.update()
		rhythm_frame(start)
	}
}

// ---- LED ----

// ledFlash はヒットしたときに LED をレーンの色で光らせ、徐々に消す。
type rhythm_ledFlash struct {
	dev   ws2812s3.Device
	c     color.RGBA
	level int // 0..255
	buf   [badge.WS2812_COUNT]color.RGBA
}

func rhythm_newLEDFlash() rhythm_ledFlash {
	leds := badge.NewLEDs()
	leds.SetBrightness(48)
	leds.WriteColors(make([]color.RGBA, badge.WS2812_COUNT))
	return rhythm_ledFlash{dev: leds}
}

func (l *rhythm_ledFlash) flash(c color.RGBA) {
	l.c = c
	l.level = 255
}

// update は 1 フレームごとに呼ぶ。消えている間は何も送らない。
func (l *rhythm_ledFlash) update() {
	if l.level <= 0 {
		return
	}
	l.level -= 40
	if l.level < 0 {
		l.level = 0
	}
	for i := range l.buf {
		l.buf[i] = rhythm_scale(l.c, l.level)
	}
	l.dev.WriteColors(l.buf[:])
}

// ---- 描画の補助 ----

func rhythm_centerText(f tinyfont.Fonter, y int16, s string, c color.RGBA) {
	rhythm_centerTextAt(f, 0, badge.LCD_WIDTH, y, s, c)
}

// centerTextAt は x から幅 w の範囲の中央に文字列を描く。
func rhythm_centerTextAt(f tinyfont.Fonter, x, w, y int16, s string, c color.RGBA) {
	_, tw := tinyfont.LineWidth(f, s)
	tinyfont.WriteLine(rhythm_screen, f, x+(w-int16(tw))/2, y, s, c)
}

func rhythm_dim(c color.RGBA) color.RGBA {
	return rhythm_scale(c, 96)
}

func rhythm_scale(c color.RGBA, level int) color.RGBA {
	return color.RGBA{
		R: uint8(int(c.R) * level / 255),
		G: uint8(int(c.G) * level / 255),
		B: uint8(int(c.B) * level / 255),
		A: 255,
	}
}

func rhythm_itoa(v int) string {
	if v == 0 {
		return "0"
	}
	neg := v < 0
	if neg {
		v = -v
	}
	var buf [12]byte
	i := len(buf)
	for v > 0 {
		i--
		buf[i] = byte('0' + v%10)
		v /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}
