// Code generated by go generate; DO NOT EDIT.
// Source: ../irlearn/main.go

// リモコンの信号を学習して送信するアプリ。
//
// 画面には登録済みのリモコン信号が一覧で並ぶ。ジョイスティックの上下で選び、
//   - SW1: 選んだ信号を送信する
//   - SW2: メニューを開く (Delete / Rename / Back)。上下で選び SW1 で決定、SW2 で戻る
//
// 一覧の末尾の "+ Register" を選んで SW1 を押すと登録モードになる。
//   - 登録モード: 受信モジュールに向けてリモコンのボタンを押すと信号を記録する。
//     SW1 で決定、SW2 でキャンセル。決定後に名前を入力する
//   - 名前入力: 左右でカーソル移動、上下で文字変更。SW1 で決定、SW2 でキャンセル
//
// 信号は受信モジュールの生のパルス長 (マイクロ秒) をそのまま記録し、38kHz の
// キャリアで再生するので、NEC 以外 (AEHA、SONY など) のリモコンにも使える。
// 登録内容はフラッシュ (flashstore) に保存され、電源を切っても残る。
package main

import (
	"image/color"
	"machine"
	"time"

	"tinygo.org/x/tinyfont"
	"tinygo.org/x/tinyfont/freesans"

	"github.com/sago35/tinygo-conf-2026-badge/firmware/badge"
)

var (
	irlearn_black  = color.RGBA{0, 0, 0, 255}
	irlearn_white  = color.RGBA{255, 255, 255, 255}
	irlearn_gray   = color.RGBA{140, 140, 140, 255}
	irlearn_dark   = color.RGBA{40, 40, 40, 255}
	irlearn_cyan   = color.RGBA{0, 200, 255, 255}
	irlearn_green  = color.RGBA{0, 255, 0, 255}
	irlearn_yellow = color.RGBA{255, 220, 0, 255}
	irlearn_red    = color.RGBA{255, 60, 60, 255}
)

// 画面の状態
type irlearn_screen int

const (
	irlearn_screenList irlearn_screen = iota
	irlearn_screenMenu
	irlearn_screenLearn
	irlearn_screenName
)

// 名前入力で使える文字
const irlearn_nameChars = " ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-"

type irlearn_app struct {
	fb *badge.Framebuffer
	tx *badge.IRTransmitter

	remotes []irlearn_Remote
	cursor  int // 一覧のカーソル (len(remotes) は "+ Register")
	scroll  int

	screen   irlearn_screen
	menuIdx  int
	message  string // 画面下部に短時間出すメッセージ
	msgUntil time.Time

	// 登録モード
	learned []uint16

	// 名前入力
	nameBuf   [irlearn_NameLen]byte
	nameCur   int
	nameIsNew bool // true なら登録の続き、false なら改名
}

func irlearn_main() {
	time.Sleep(500 * time.Millisecond)
	display := badge.NewDisplay()
	a := &irlearn_app{fb: badge.NewFramebuffer(display)}
	in := irlearn_newInput()

	tx, err := badge.NewIRTransmitter()
	if err != nil {
		println("ir tx init:", err.Error())
		select {}
	}
	a.tx = tx
	badge.IR_DATA.Configure(machine.PinConfig{Mode: machine.PinInputPullup})

	a.remotes = irlearn_loadRemotes()
	println("loaded", len(a.remotes), "remotes")
	a.draw()

	for {
		ev := in.poll()
		changed := false
		switch a.screen {
		case irlearn_screenList:
			changed = a.handleList(ev)
		case irlearn_screenMenu:
			changed = a.handleMenu(ev)
		case irlearn_screenLearn:
			changed = a.handleLearn(ev)
		case irlearn_screenName:
			changed = a.handleName(ev)
		}
		if a.message != "" && time.Now().After(a.msgUntil) {
			a.message = ""
			changed = true
		}
		if changed {
			a.draw()
		}
		time.Sleep(20 * time.Millisecond)
	}
}

func (a *irlearn_app) show(msg string) {
	a.message = msg
	a.msgUntil = time.Now().Add(1500 * time.Millisecond)
}

// ---- 一覧 ----

func (a *irlearn_app) handleList(ev irlearn_input) bool {
	items := len(a.remotes) + 1 // 末尾は "+ Register"
	switch {
	case ev.up:
		if a.cursor > 0 {
			a.cursor--
		}
	case ev.down:
		if a.cursor < items-1 {
			a.cursor++
		}
	case ev.sw1:
		if a.cursor == len(a.remotes) {
			a.screen = irlearn_screenLearn
			a.learned = nil
			irlearn_startCapture()
			return true
		}
		r := a.remotes[a.cursor]
		println("send:", r.Name, len(r.Pulses), "pulses")
		a.tx.SendRaw(r.Pulses)
		a.show("Sent: " + r.Name)
	case ev.sw2:
		if a.cursor < len(a.remotes) {
			a.screen = irlearn_screenMenu
			a.menuIdx = 0
		}
	default:
		return false
	}
	return true
}

// ---- メニュー ----

var irlearn_menuItems = []string{"Delete", "Rename", "Back"}

func (a *irlearn_app) handleMenu(ev irlearn_input) bool {
	switch {
	case ev.up:
		if a.menuIdx > 0 {
			a.menuIdx--
		}
	case ev.down:
		if a.menuIdx < len(irlearn_menuItems)-1 {
			a.menuIdx++
		}
	case ev.sw2:
		a.screen = irlearn_screenList
	case ev.sw1:
		switch a.menuIdx {
		case 0: // Delete
			name := a.remotes[a.cursor].Name
			a.remotes = append(a.remotes[:a.cursor], a.remotes[a.cursor+1:]...)
			if a.cursor > len(a.remotes) {
				a.cursor = len(a.remotes)
			}
			a.save()
			a.show("Deleted: " + name)
			a.screen = irlearn_screenList
		case 1: // Rename
			a.startNameEdit(a.remotes[a.cursor].Name, false)
		default:
			a.screen = irlearn_screenList
		}
	default:
		return false
	}
	return true
}

// ---- 登録 (受信待ち) ----

func (a *irlearn_app) handleLearn(ev irlearn_input) bool {
	changed := false
	if p := irlearn_captured(); p != nil {
		a.learned = p
		println("captured", len(p), "pulses")
		changed = true
	}
	switch {
	case ev.sw2:
		irlearn_stopCapture()
		a.learned = nil
		a.screen = irlearn_screenList
		return true
	case ev.sw1:
		if a.learned == nil {
			return changed
		}
		irlearn_stopCapture()
		a.startNameEdit("", true)
		return true
	}
	return changed
}

// ---- 名前入力 ----

func (a *irlearn_app) startNameEdit(initial string, isNew bool) {
	for i := range a.nameBuf {
		a.nameBuf[i] = ' '
	}
	copy(a.nameBuf[:], initial)
	a.nameCur = 0
	a.nameIsNew = isNew
	a.screen = irlearn_screenName
}

func (a *irlearn_app) handleName(ev irlearn_input) bool {
	switch {
	case ev.left:
		if a.nameCur > 0 {
			a.nameCur--
		}
	case ev.right:
		if a.nameCur < irlearn_NameLen-1 {
			a.nameCur++
		}
	case ev.up, ev.down:
		idx := irlearn_indexOf(irlearn_nameChars, a.nameBuf[a.nameCur])
		if ev.up {
			idx = (idx + 1) % len(irlearn_nameChars)
		} else {
			idx = (idx + len(irlearn_nameChars) - 1) % len(irlearn_nameChars)
		}
		a.nameBuf[a.nameCur] = irlearn_nameChars[idx]
	case ev.sw2:
		a.learned = nil
		a.screen = irlearn_screenList
	case ev.sw1:
		name := irlearn_trimRight(a.nameBuf[:])
		if name == "" {
			name = "REMOTE"
		}
		if a.nameIsNew {
			if len(a.remotes) >= irlearn_MaxRemotes {
				a.show("Full (max 24)")
			} else {
				a.remotes = append(a.remotes, irlearn_Remote{Name: name, Pulses: a.learned})
				a.cursor = len(a.remotes) - 1
				a.show("Registered: " + name)
			}
			a.learned = nil
		} else {
			a.remotes[a.cursor].Name = name
			a.show("Renamed: " + name)
		}
		a.save()
		a.screen = irlearn_screenList
	default:
		return false
	}
	return true
}

func (a *irlearn_app) save() {
	if err := irlearn_saveRemotes(a.remotes); err != nil {
		println("save error:", err.Error())
		a.show(err.Error())
	}
}

// ---- 描画 ----

const (
	irlearn_lineH     = 18
	irlearn_listTop   = 40
	irlearn_listLines = 9
)

func (a *irlearn_app) draw() {
	fb := a.fb
	w, h := fb.Size()
	fb.FillScreen(irlearn_black)
	tinyfont.WriteLine(fb, &freesans.Bold12pt7b, 8, 24, "IR Remote", irlearn_white)

	switch a.screen {
	case irlearn_screenList, irlearn_screenMenu:
		a.drawList()
		if a.screen == irlearn_screenMenu {
			a.drawMenu()
		}
		tinyfont.WriteLine(fb, &freesans.Regular9pt7b, 8, h-8, "SW1: send   SW2: menu", irlearn_gray)
	case irlearn_screenLearn:
		tinyfont.WriteLine(fb, &freesans.Regular9pt7b, 8, 60, "Point the remote at the", irlearn_white)
		tinyfont.WriteLine(fb, &freesans.Regular9pt7b, 8, 80, "sensor and press a key.", irlearn_white)
		if a.learned == nil {
			tinyfont.WriteLine(fb, &freesans.Bold12pt7b, 8, 130, "waiting...", irlearn_yellow)
		} else {
			tinyfont.WriteLine(fb, &freesans.Bold12pt7b, 8, 130, "captured "+irlearn_itoa(len(a.learned))+" pulses", irlearn_green)
			tinyfont.WriteLine(fb, &freesans.Regular9pt7b, 8, 155, "press again to re-capture", irlearn_gray)
		}
		tinyfont.WriteLine(fb, &freesans.Regular9pt7b, 8, h-8, "SW1: OK   SW2: cancel", irlearn_gray)
	case irlearn_screenName:
		title := "Name (new)"
		if !a.nameIsNew {
			title = "Rename"
		}
		tinyfont.WriteLine(fb, &freesans.Regular9pt7b, 8, 60, title, irlearn_white)
		// 1 文字ずつ等間隔に描き、カーソル位置に下線
		const cw = 17
		x0 := int16(10)
		for i, c := range a.nameBuf {
			x := x0 + int16(i)*cw
			col := irlearn_white
			if i == a.nameCur {
				fb.FillRectangle(x-2, 100, cw-2, 3, irlearn_cyan)
				col = irlearn_cyan
			}
			tinyfont.WriteLine(fb, &freesans.Bold12pt7b, x, 95, string(c), col)
		}
		tinyfont.WriteLine(fb, &freesans.Regular9pt7b, 8, 140, "left/right: cursor", irlearn_gray)
		tinyfont.WriteLine(fb, &freesans.Regular9pt7b, 8, 160, "up/down: character", irlearn_gray)
		tinyfont.WriteLine(fb, &freesans.Regular9pt7b, 8, h-8, "SW1: OK   SW2: cancel", irlearn_gray)
	}

	if a.message != "" {
		fb.FillRectangle(0, h-52, w, 24, irlearn_dark)
		tinyfont.WriteLine(fb, &freesans.Regular9pt7b, 8, h-36, a.message, irlearn_yellow)
	}
	fb.Display()
}

func (a *irlearn_app) drawList() {
	fb := a.fb
	w, _ := fb.Size()
	items := len(a.remotes) + 1
	// カーソルが見えるようにスクロール
	if a.cursor < a.scroll {
		a.scroll = a.cursor
	}
	if a.cursor >= a.scroll+irlearn_listLines {
		a.scroll = a.cursor - irlearn_listLines + 1
	}
	for row := 0; row < irlearn_listLines; row++ {
		i := a.scroll + row
		if i >= items {
			break
		}
		y := int16(irlearn_listTop + row*irlearn_lineH)
		label := "+ Register"
		col := irlearn_cyan
		if i < len(a.remotes) {
			label = a.remotes[i].Name
			col = irlearn_white
		}
		if i == a.cursor {
			fb.FillRectangle(4, y, w-8, irlearn_lineH, irlearn_dark)
			tinyfont.WriteLine(fb, &freesans.Regular9pt7b, 8, y+13, ">", irlearn_yellow)
		}
		tinyfont.WriteLine(fb, &freesans.Regular9pt7b, 22, y+13, label, col)
	}
	if items > irlearn_listLines {
		tinyfont.WriteLine(fb, &freesans.Regular9pt7b, w-40, irlearn_listTop+13, irlearn_itoa(a.cursor+1)+"/"+irlearn_itoa(items), irlearn_gray)
	}
}

func (a *irlearn_app) drawMenu() {
	fb := a.fb
	w, _ := fb.Size()
	const mw, mh = 120, 3*irlearn_lineH + 16
	x := (w - mw) / 2
	y := int16(90)
	fb.FillRectangle(x-2, y-2, mw+4, mh+4, irlearn_gray)
	fb.FillRectangle(x, y, mw, mh, irlearn_black)
	for i, item := range irlearn_menuItems {
		yy := y + 8 + int16(i)*irlearn_lineH
		col := irlearn_white
		if i == a.menuIdx {
			fb.FillRectangle(x+4, yy, mw-8, irlearn_lineH, irlearn_dark)
			col = irlearn_yellow
		}
		tinyfont.WriteLine(fb, &freesans.Regular9pt7b, x+12, yy+13, item, col)
	}
}

// ---- 入力 ----

// input は 1 回のポーリングで検出したイベント (押した瞬間、または上下左右の 1 ステップ)。
type irlearn_input struct {
	sw1, sw2              bool
	up, down, left, right bool
}

type irlearn_inputState struct {
	sw1, sw2   badge.Button
	joy        *badge.Joystick
	prev1      bool
	prev2      bool
	dirHeld    int // 0 なし、1 上、2 下、3 左、4 右
	nextRepeat time.Time
}

func irlearn_newInput() *irlearn_inputState {
	sw1, sw2 := badge.NewButtons()
	joy := badge.NewJoystick()
	joy.Calibrate(300 * time.Millisecond)
	return &irlearn_inputState{sw1: sw1, sw2: sw2, joy: joy}
}

const (
	irlearn_dirThreshold = 500
	irlearn_repeatFirst  = 400 * time.Millisecond
	irlearn_repeatNext   = 120 * time.Millisecond
)

func (s *irlearn_inputState) poll() irlearn_input {
	var ev irlearn_input
	p1, p2 := s.sw1.Pressed(), s.sw2.Pressed()
	ev.sw1 = p1 && !s.prev1
	ev.sw2 = p2 && !s.prev2
	s.prev1, s.prev2 = p1, p2

	x, y, _ := s.joy.Read()
	dir := 0
	switch {
	case y > irlearn_dirThreshold:
		dir = 1
	case y < -irlearn_dirThreshold:
		dir = 2
	case x < -irlearn_dirThreshold:
		dir = 3
	case x > irlearn_dirThreshold:
		dir = 4
	}
	fire := false
	if dir != s.dirHeld {
		s.dirHeld = dir
		if dir != 0 {
			fire = true
			s.nextRepeat = time.Now().Add(irlearn_repeatFirst)
		}
	} else if dir != 0 && time.Now().After(s.nextRepeat) {
		fire = true
		s.nextRepeat = time.Now().Add(irlearn_repeatNext)
	}
	if fire {
		switch dir {
		case 1:
			ev.up = true
		case 2:
			ev.down = true
		case 3:
			ev.left = true
		case 4:
			ev.right = true
		}
	}
	return ev
}

// ---- 小物 ----

func irlearn_indexOf(s string, c byte) int {
	for i := 0; i < len(s); i++ {
		if s[i] == c {
			return i
		}
	}
	return 0
}

func irlearn_trimRight(b []byte) string {
	n := len(b)
	for n > 0 && (b[n-1] == ' ' || b[n-1] == 0) {
		n--
	}
	return string(b[:n])
}

func irlearn_itoa(v int) string {
	if v == 0 {
		return "0"
	}
	neg := v < 0
	if neg {
		v = -v
	}
	var buf [12]byte
	i := len(buf)
	for v > 0 {
		i--
		buf[i] = byte('0' + v%10)
		v /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}
