// Code generated by go generate; DO NOT EDIT.
// Source: ../wifi-server/main.go
// Launcher input adaptations are defined in generate.go.

// Wi-Fi に接続して HTTP サーバーを立ち上げ、基板上の AHT21B の温湿度を返す。
//
//	/         温湿度を表示する HTML ページ (2 秒ごとに /api を取得して更新)
//	/api      {"temperature":25.3,"humidity":48.2} 形式の JSON
//	/metrics  Prometheus 形式のテキスト
//
// SSID とパスワードはビルド時に ldflags で埋め込む。
//
//	make flash-wifi-server SSID=yourssid PASS=yourpassword
//
// HTTP サーバーには espradio 推奨の httphi (リクエストごとにヒープを使わない) を使う。
package main

import (
	"strconv"
	"sync"
	"time"

	"github.com/soypat/lneto/http/httphi"
	"tinygo.org/x/drivers/netdev"
	link "tinygo.org/x/espradio/netlink"

	"github.com/sago35/tinygo-conf-2026-badge/firmware/badge"
	"github.com/sago35/tinygo-conf-2026-badge/firmware/wifi"
)

const wifi_server_port uint16 = 80

// センサーの最新値。読み取りは 1 つの goroutine だけが行い、
// HTTP ハンドラは mu を取ってコピーを読む。
var (
	wifi_server_mu       sync.Mutex
	wifi_server_deciTemp int32 // 0.1 度単位
	wifi_server_deciHum  int32 // 0.1% 単位
	wifi_server_readErr  error
	wifi_server_readAt   time.Time
)

const wifi_server_indexHTML = `<!doctype html>
<html lang="ja"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>TinyGo Conf 2026 badge</title>
<style>
body{font-family:sans-serif;margin:2em;background:#111;color:#eee}
.v{font-size:3em;font-weight:bold}
.u{font-size:1em;color:#999}
</style></head><body>
<h1>TinyGo Conf 2026 badge</h1>
<p>AHT21B</p>
<div><span id="t" class="v">--</span><span class="u"> &deg;C</span></div>
<div><span id="h" class="v">--</span><span class="u"> %RH</span></div>
<p id="s" class="u"></p>
<script>
async function update(){
  try{
    const r=await fetch('/api');const j=await r.json();
    document.getElementById('t').textContent=j.temperature.toFixed(1);
    document.getElementById('h').textContent=j.humidity.toFixed(1);
    document.getElementById('s').textContent='updated '+new Date().toLocaleTimeString();
  }catch(e){document.getElementById('s').textContent='error: '+e;}
}
update();setInterval(update,2000);
</script></body></html>`

func wifi_server_main() {
	time.Sleep(2 * time.Second)
	if ssid == "" {
		wifi_server_failure("ssid is empty: build with -ldflags=\"-X main.ssid=... -X main.password=...\"")
	}

	sensor := badge.NewSensor()
	go func() {
		for {
			err := sensor.Read()
			wifi_server_mu.Lock()
			wifi_server_readErr = err
			if err == nil {
				wifi_server_deciTemp = sensor.DeciCelsius()
				wifi_server_deciHum = sensor.DeciRelHumidity()
				wifi_server_readAt = time.Now()
			}
			wifi_server_mu.Unlock()
			time.Sleep(2 * time.Second)
		}
	}()

	// 接続に失敗した場合はリセットして最初からやり直す (成功するまで戻らない)
	link := &link.Esplink{}
	netdev.UseNetdev(link)
	wifi.Connect(link, ssid, password)

	var mux httphi.MuxSlice
	mux.Handle("/", wifi_server_logRequest(wifi_server_index))
	mux.Handle("/api", wifi_server_logRequest(wifi_server_api))
	mux.Handle("/metrics", wifi_server_logRequest(wifi_server_metrics))

	var router httphi.Router
	cfg := httphi.DefaultRouterConfig(4, 2048, mux.MaxPathValues())
	wifi_server_failIfErr("router configure", router.Configure(&mux, cfg))
	defer router.Shutdown()

	addr, err := link.Addr()
	wifi_server_failIfErr("link.Addr", err)
	print("HTTP server listening on http://", addr.String(), ":", wifi_server_port, "\n")
	wifi_server_failIfErr("ListenAndServe", link.ListenAndServe(&router, wifi_server_port))
}

func wifi_server_logRequest(h httphi.HandlerFunc) httphi.HandlerFunc {
	return func(exch *httphi.Exchange) {
		println(exch.RequestMethod().String(), exch.MuxPattern())
		h(exch)
	}
}

func wifi_server_index(exch *httphi.Exchange) {
	exch.RespondString(httphi.StatusOK, "text/html; charset=utf-8", wifi_server_indexHTML)
}

// レスポンス組み立て用の固定バッファ。ハンドラごとに確保しない。
var (
	wifi_server_bufMu sync.Mutex
	wifi_server_buf   [160]byte
)

func wifi_server_snapshot() (t, h int32, err error, age time.Duration) {
	wifi_server_mu.Lock()
	defer wifi_server_mu.Unlock()
	return wifi_server_deciTemp, wifi_server_deciHum, wifi_server_readErr, time.Since(wifi_server_readAt)
}

func wifi_server_api(exch *httphi.Exchange) {
	t, h, err, _ := wifi_server_snapshot()
	wifi_server_bufMu.Lock()
	defer wifi_server_bufMu.Unlock()
	if err != nil {
		exch.RespondString(httphi.StatusInternalServerError, "application/json", `{"error":"sensor read failed"}`)
		return
	}
	b := append(wifi_server_buf[:0], `{"temperature":`...)
	b = wifi_server_appendDeci(b, t)
	b = append(b, `,"humidity":`...)
	b = wifi_server_appendDeci(b, h)
	b = append(b, '}')
	exch.Respond(httphi.StatusOK, "application/json", b)
}

func wifi_server_metrics(exch *httphi.Exchange) {
	t, h, err, _ := wifi_server_snapshot()
	wifi_server_bufMu.Lock()
	defer wifi_server_bufMu.Unlock()
	if err != nil {
		exch.RespondString(httphi.StatusInternalServerError, "text/plain", "sensor read failed\n")
		return
	}
	b := append(wifi_server_buf[:0], "badge_temperature_celsius "...)
	b = wifi_server_appendDeci(b, t)
	b = append(b, "\nbadge_humidity_percent "...)
	b = wifi_server_appendDeci(b, h)
	b = append(b, '\n')
	exch.Respond(httphi.StatusOK, "text/plain; version=0.0.4", b)
}

// appendDeci は 0.1 単位の整数を "12.3" 形式で追記する。
func wifi_server_appendDeci(b []byte, v int32) []byte {
	if v < 0 {
		b = append(b, '-')
		v = -v
	}
	b = strconv.AppendInt(b, int64(v/10), 10)
	b = append(b, '.')
	return strconv.AppendInt(b, int64(v%10), 10)
}

func wifi_server_failIfErr(action string, err error) {
	for err != nil {
		println("fail", action+":", err.Error())
		time.Sleep(time.Second)
	}
}

func wifi_server_failure(msg string) {
	for {
		println("failure:", msg)
		time.Sleep(time.Second)
	}
}
