// Code generated by go generate; DO NOT EDIT.
// Source: ../slotgame/slot.go

package main

// Ported from sat0ken/tinygo-slotgame, commit
// e61ecf541d6ef2643899a1041f0d8602801aa867. See README.md for attribution.

// ハードウェアに依存しない部分（図柄の描画、リール、役判定、ゲーム進行）。
// machine や液晶ドライバを import しないので、ホストの Go でもテスト・画像出力できる。

import (
	_ "embed"
	"image/color"
	"strconv"
	"time"

	"tinygo.org/x/drivers"
	"tinygo.org/x/drivers/pixel"
	"tinygo.org/x/tinyfont"
	"tinygo.org/x/tinyfont/freesans"
)

const (
	slotgame_screenH = 240

	slotgame_symH        = 50
	slotgame_visibleRows = 3
	slotgame_reelH       = slotgame_symH * slotgame_visibleRows
	slotgame_reelY       = 42

	slotgame_spinSpeed   = 12 // 1フレームで進むピクセル数
	slotgame_frameTime   = 30 * time.Millisecond
	slotgame_stopLockout = 300 * time.Millisecond

	slotgame_bet         = 3
	slotgame_startCredit = 50

	slotgame_msgY     = 196
	slotgame_msgH     = 23
	slotgame_labelY   = 221
	slotgame_labelH   = 19
	slotgame_markerCY = 117
)

// layout は画面の幅によって変わる配置。縦方向の配置はどの画面も共通（高さ 240）。
type slotgame_layout struct {
	screenW  int16
	symW     int      // 1コマの幅
	reelX    [3]int16 // 各リールの左端
	markerX  int16    // 左の三角マーカーの左端（右は左右対称）
	markerW  int16    // 三角マーカーの幅
	gameOver string   // GAME OVER のメッセージ
}

var (
	// 320×240（M5Stack, Wio Terminal）。リールの中心をボタン A/B/C の真上に合わせる。
	slotgame_layoutWide = slotgame_layout{
		screenW:  320,
		symW:     84,
		reelX:    [3]int16{26, 118, 210},
		markerX:  8,
		markerW:  10,
		gameOver: "GAME OVER - PRESS SW1",
	}
	// 240×240（RP2040-Zero + ST7789）。リールを細くし、長いメッセージは短くする。
	slotgame_layoutSquare = slotgame_layout{
		screenW:  240,
		symW:     70,
		reelX:    [3]int16{8, 85, 162},
		markerX:  0,
		markerW:  5,
		gameOver: "GAME OVER",
	}
)

// 図柄
const (
	slotgame_symSeven uint8 = iota
	slotgame_symBar
	slotgame_symBell  // 見た目は茶色の Gopher（img/Gogophercolor.png）
	slotgame_symGrape // 見た目は青い Gopher（img/gopher.svg）
	slotgame_symCherry
	slotgame_symTinyGo
	slotgame_numSymbols
)

var slotgame_strips = [3][]uint8{
	{slotgame_symSeven, slotgame_symGrape, slotgame_symCherry, slotgame_symBell, slotgame_symGrape, slotgame_symBar, slotgame_symCherry, slotgame_symGrape, slotgame_symBell, slotgame_symGrape, slotgame_symCherry, slotgame_symBell, slotgame_symTinyGo},
	{slotgame_symSeven, slotgame_symBell, slotgame_symGrape, slotgame_symBar, slotgame_symGrape, slotgame_symBell, slotgame_symCherry, slotgame_symGrape, slotgame_symBell, slotgame_symGrape, slotgame_symBar, slotgame_symGrape, slotgame_symTinyGo},
	{slotgame_symSeven, slotgame_symGrape, slotgame_symBell, slotgame_symGrape, slotgame_symBar, slotgame_symBell, slotgame_symGrape, slotgame_symCherry, slotgame_symBell, slotgame_symGrape, slotgame_symBar, slotgame_symGrape, slotgame_symTinyGo},
}

// 色
var (
	slotgame_colBG      = color.RGBA{18, 18, 40, 255}
	slotgame_colFrame   = color.RGBA{200, 170, 60, 255}
	slotgame_colCell    = color.RGBA{250, 246, 232, 255}
	slotgame_colDivider = color.RGBA{215, 210, 195, 255}
	slotgame_colLine    = color.RGBA{230, 30, 30, 255}
	slotgame_colYellow  = color.RGBA{255, 220, 40, 255}
	slotgame_colRed     = color.RGBA{220, 30, 30, 255}
	slotgame_colGray    = color.RGBA{90, 90, 110, 255}
	slotgame_colWhite   = color.RGBA{255, 255, 255, 255}
	slotgame_colBlack   = color.RGBA{0, 0, 0, 255}

	slotgame_colDarkRed     = color.RGBA{120, 0, 0, 255}
	slotgame_colGold        = color.RGBA{255, 190, 0, 255}
	slotgame_colOrange      = color.RGBA{230, 110, 0, 255}
	slotgame_colPurple      = color.RGBA{120, 40, 170, 255}
	slotgame_colLightPurple = color.RGBA{200, 150, 230, 255}
	slotgame_colGreen       = color.RGBA{40, 150, 50, 255}
)

// screen は液晶ドライバ（ili9341, st7789）のうち、このゲームが使うメソッドだけを抜き出したもの。
type slotgame_screen interface {
	drivers.Displayer
	FillRectangle(x, y, width, height int16, c color.RGBA) error
	DrawBitmap(x, y int16, bitmap pixel.Image[pixel.RGB565BE]) error
}

// ---- 図柄の事前描画 ----

// canvas は pixel.Image に描くための drivers.Displayer。tinyfont からも使える。
// 図柄は幅 84 のコマを基準にした座標で描き、ox だけ横にずらして実際の幅のコマに収める。
type slotgame_canvas struct {
	img pixel.Image[pixel.RGB565BE]
	ox  int
}

func (c slotgame_canvas) Size() (int16, int16) {
	w, h := c.img.Size()
	return int16(w), int16(h)
}

func (c slotgame_canvas) SetPixel(x, y int16, col color.RGBA) {
	x += int16(c.ox)
	w, h := c.img.Size()
	if x < 0 || y < 0 || int(x) >= w || int(y) >= h {
		return
	}
	c.img.Set(int(x), int(y), pixel.NewColor[pixel.RGB565BE](col.R, col.G, col.B))
}

func (c slotgame_canvas) Display() error { return nil }

func (c slotgame_canvas) fillRect(x, y, w, h int, col color.RGBA) {
	for yy := y; yy < y+h; yy++ {
		for xx := x; xx < x+w; xx++ {
			c.SetPixel(int16(xx), int16(yy), col)
		}
	}
}

func (c slotgame_canvas) fillCircle(cx, cy, r int, col color.RGBA) {
	for dy := -r; dy <= r; dy++ {
		for dx := -r; dx <= r; dx++ {
			if dx*dx+dy*dy <= r*r {
				c.SetPixel(int16(cx+dx), int16(cy+dy), col)
			}
		}
	}
}

// line は半径 r の円を線上に並べて太線を描く。
func (c slotgame_canvas) line(x0, y0, x1, y1, r int, col color.RGBA) {
	dx, dy := x1-x0, y1-y0
	steps := max(slotgame_abs(dx), slotgame_abs(dy))
	if steps == 0 {
		c.fillCircle(x0, y0, r, col)
		return
	}
	for i := 0; i <= steps; i++ {
		c.fillCircle(x0+dx*i/steps, y0+dy*i/steps, r, col)
	}
}

func (c slotgame_canvas) textCentered(font tinyfont.Fonter, cx, baseline int, s string, col color.RGBA) {
	_, w := tinyfont.LineWidth(font, s)
	tinyfont.WriteLine(c, font, int16(cx-int(w)/2), int16(baseline), s, col)
}

// 図柄のスプライト。tools/gensprite で作る（形式は [幅, 高さ] + RGBA）。
// string で埋め込むと TinyGo では flash に置かれ、RAM を使わない。
var (
	//go:embed assets/slotgame/img/gopher_blue.rgba
	slotgame_gopherBlue string
	//go:embed assets/slotgame/img/gopher_brown.rgba
	slotgame_gopherBrown string
	//go:embed assets/slotgame/img/tinygo.rgba
	slotgame_tinygoLogo string
)

// sprite はスプライトを中心 x=cx、上端 y=top に、コマ地の色と合成して描く。
func (c slotgame_canvas) sprite(cx, top int, data string) {
	w, h := int(data[0]), int(data[1])
	px := data[2:]
	x0 := cx - w/2
	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			i := (y*w + x) * 4
			a := int(px[i+3])
			if a == 0 {
				continue
			}
			c.SetPixel(int16(x0+x), int16(top+y), color.RGBA{
				slotgame_blend(px[i], slotgame_colCell.R, a),
				slotgame_blend(px[i+1], slotgame_colCell.G, a),
				slotgame_blend(px[i+2], slotgame_colCell.B, a),
				255,
			})
		}
	}
}

func slotgame_blend(fg, bg uint8, a int) uint8 {
	return uint8((int(fg)*a + int(bg)*(255-a) + 127) / 255)
}

func slotgame_abs(v int) int {
	if v < 0 {
		return -v
	}
	return v
}

func slotgame_makeSymbols(symW int) [slotgame_numSymbols]pixel.Image[pixel.RGB565BE] {
	var imgs [slotgame_numSymbols]pixel.Image[pixel.RGB565BE]
	for i := range imgs {
		imgs[i] = pixel.NewImage[pixel.RGB565BE](symW, slotgame_symH)
		bg := slotgame_canvas{img: imgs[i]}
		bg.fillRect(0, 0, symW, slotgame_symH, slotgame_colCell)
		bg.fillRect(0, slotgame_symH-1, symW, 1, slotgame_colDivider)
		slotgame_drawSymbol(slotgame_canvas{img: imgs[i], ox: symW/2 - 42}, uint8(i))
	}
	return imgs
}

func slotgame_drawSymbol(c slotgame_canvas, sym uint8) {
	switch sym {
	case slotgame_symSeven:
		c.textCentered(&freesans.Bold24pt7b, 44, 44, "7", slotgame_colDarkRed)
		c.textCentered(&freesans.Bold24pt7b, 42, 42, "7", slotgame_colRed)
	case slotgame_symBar:
		// 枠はコマの幅に合わせる（幅 84 で 68）。収まらなければ文字を小さくする。
		w, _ := c.img.Size()
		bw := w - 16
		x := 42 - bw/2
		c.fillRect(x, 11, bw, 28, slotgame_colBlack)
		c.fillRect(x+2, 13, bw-4, 2, slotgame_colWhite)
		c.fillRect(x+2, 35, bw-4, 2, slotgame_colWhite)
		if _, tw := tinyfont.LineWidth(&freesans.Bold12pt7b, "BAR"); int(tw)+10 <= bw {
			c.textCentered(&freesans.Bold12pt7b, 42, 33, "BAR", slotgame_colWhite)
		} else {
			c.textCentered(&freesans.Bold9pt7b, 42, 31, "BAR", slotgame_colWhite)
		}
	case slotgame_symBell:
		c.sprite(42, 3, slotgame_gopherBrown)
	case slotgame_symGrape:
		c.sprite(42, 3, slotgame_gopherBlue)
	case slotgame_symTinyGo:
		c.sprite(42, 3, slotgame_tinygoLogo)
	case slotgame_symCherry:
		c.line(30, 28, 46, 7, 1, slotgame_colGreen)
		c.line(54, 26, 46, 7, 1, slotgame_colGreen)
		c.fillCircle(53, 8, 4, slotgame_colGreen)
		c.fillCircle(30, 36, 9, slotgame_colRed)
		c.fillCircle(54, 34, 9, slotgame_colRed)
		c.fillCircle(27, 33, 2, slotgame_colWhite)
		c.fillCircle(51, 31, 2, slotgame_colWhite)
	}
}

// ---- リール ----

type slotgame_reel struct {
	strip    []uint8 // リール配列
	offset   int     // 0 .. len(strip)*symH-1。増えると図柄が下に流れる
	spinning bool
	stopping bool
	remain   int // 停止までに進む残りピクセル
}

func (r *slotgame_reel) total() int { return len(r.strip) * slotgame_symH }

func (r *slotgame_reel) start() {
	r.spinning = true
	r.stopping = false
	r.remain = 0
}

// requestStop は次のコマ境界で止まるよう停止要求を出す（最大1コマ滑り）。
func (r *slotgame_reel) requestStop() {
	if !r.spinning || r.stopping {
		return
	}
	r.stopping = true
	r.remain = (slotgame_symH - r.offset%slotgame_symH) % slotgame_symH
}

// update は1フレーム分進め、描き直しが必要なら true を返す。
func (r *slotgame_reel) update() bool {
	if !r.spinning {
		return false
	}
	step := slotgame_spinSpeed
	if r.stopping {
		step = min(slotgame_spinSpeed, r.remain)
		r.remain -= step
	}
	r.offset = (r.offset + step) % r.total()
	if r.stopping && r.remain == 0 {
		r.spinning = false
		r.stopping = false
	}
	return true
}

// center は中段の図柄を返す（停止中のみ意味がある）。
func (r *slotgame_reel) center() uint8 {
	t := r.total()
	return r.strip[((slotgame_symH-r.offset)%t+t)%t/slotgame_symH]
}

// render はリールの見えている部分を buf（コマ幅×150）に描く。
func (r *slotgame_reel) render(buf pixel.Image[pixel.RGB565BE], syms *[slotgame_numSymbols]pixel.Image[pixel.RGB565BE]) {
	w, _ := buf.Size()
	rowBytes := w * 2
	dst := buf.RawBuffer()
	t := r.total()
	for y := 0; y < slotgame_reelH; y++ {
		s := ((y-r.offset)%t + t) % t
		src := syms[r.strip[s/slotgame_symH]].RawBuffer()
		row := s % slotgame_symH
		copy(dst[y*rowBytes:(y+1)*rowBytes], src[row*rowBytes:(row+1)*rowBytes])
	}
	v := pixel.NewColor[pixel.RGB565BE](slotgame_colLine.R, slotgame_colLine.G, slotgame_colLine.B)
	for _, y := range [2]int{slotgame_symH - 1, slotgame_symH * 2} {
		line := dst[y*rowBytes : (y+1)*rowBytes]
		for x := 0; x < rowBytes; x += 2 {
			line[x] = byte(v)
			line[x+1] = byte(v >> 8)
		}
	}
}

// ---- 役判定 ----

// judge は中段の3図柄から配当とメッセージを返す。上から順に最初に当てはまった役のみ。
func slotgame_judge(l, c, r uint8) (int, string) {
	switch {
	case l == slotgame_symSeven && c == slotgame_symSeven && r == slotgame_symSeven:
		return 100, "BIG BONUS!! +100"
	case l == slotgame_symBar && c == slotgame_symBar && r == slotgame_symBar:
		return 50, "BAR BAR BAR! +50"
	case l == slotgame_symTinyGo && c == slotgame_symTinyGo && r == slotgame_symTinyGo:
		return 25, "TINYGO!! +25"
	case l == slotgame_symBell && c == slotgame_symBell && r == slotgame_symBell:
		return 15, "BROWN GOPHER +15"
	case l == slotgame_symCherry && c == slotgame_symCherry && r == slotgame_symCherry:
		return 10, "CHERRY x3 +10"
	case l == slotgame_symGrape && c == slotgame_symGrape && r == slotgame_symGrape:
		return 8, "BLUE GOPHER +8"
	case l == slotgame_symCherry:
		return 2, "CHERRY +2"
	}
	return 0, "PRESS SW1"
}

// ---- ゲーム ----

const (
	slotgame_stateIdle = iota
	slotgame_stateSpinning
	slotgame_stateGameOver
)

type slotgame_game struct {
	scr       slotgame_screen
	lay       slotgame_layout
	oneButton bool // true ならボタン 1 つで、押すたびに左のリールから順に止める
	syms      [slotgame_numSymbols]pixel.Image[pixel.RGB565BE]
	reelImg   pixel.Image[pixel.RGB565BE]
	reels     [3]slotgame_reel
	state     int
	credit    int
	spinStart time.Time
}

func slotgame_newGame(scr slotgame_screen, lay slotgame_layout) *slotgame_game {
	g := &slotgame_game{scr: scr, lay: lay, credit: slotgame_startCredit}
	g.syms = slotgame_makeSymbols(lay.symW)
	g.reelImg = pixel.NewImage[pixel.RGB565BE](lay.symW, slotgame_reelH)
	for i := range g.reels {
		g.reels[i].strip = slotgame_strips[i]
	}
	g.drawStatic()
	g.drawCredit()
	for i := range g.reels {
		g.drawReel(i)
	}
	g.drawLabels()
	g.drawMessage("PRESS SW1", slotgame_colYellow)
	return g
}

// edges は押された瞬間（前フレームで離されていて、今フレームで押されている）だけを true にする。
// フレーム周期でサンプリングするので、チャタリング対策も兼ねる。
func slotgame_edges(down [3]bool, prev *[3]bool) [3]bool {
	var pressed [3]bool
	for i := range down {
		pressed[i] = down[i] && !prev[i]
	}
	*prev = down
	return pressed
}

// step は1フレーム分の処理。pressed は各ボタンがこのフレームで押された瞬間かどうか。
func (g *slotgame_game) step(pressed [3]bool, now time.Time) {
	anyPressed := pressed[0] || pressed[1] || pressed[2]
	switch g.state {
	case slotgame_stateIdle:
		if !anyPressed {
			return
		}
		g.credit -= slotgame_bet
		g.drawCredit()
		g.clearMessage()
		g.spinStart = now
		for i := range g.reels {
			g.reels[i].start()
		}
		g.drawLabels()
		g.state = slotgame_stateSpinning

	case slotgame_stateSpinning:
		if now.Sub(g.spinStart) >= slotgame_stopLockout {
			if g.oneButton {
				if i := g.nextReel(); anyPressed && i >= 0 {
					g.reels[i].requestStop()
					g.drawLabels()
				}
			} else {
				for i, p := range pressed {
					if p {
						g.reels[i].requestStop()
					}
				}
			}
		}
		allStopped := true
		for i := range g.reels {
			r := &g.reels[i]
			wasSpinning := r.spinning
			if r.update() {
				g.drawReel(i)
			}
			if wasSpinning && !r.spinning {
				g.drawLabel(i)
			}
			if r.spinning {
				allStopped = false
			}
		}
		if allStopped {
			g.finishSpin()
		}

	case slotgame_stateGameOver:
		if !anyPressed {
			return
		}
		g.credit = slotgame_startCredit
		g.drawCredit()
		g.drawMessage("PRESS SW1", slotgame_colYellow)
		g.state = slotgame_stateIdle
	}
}

// nextReel は 1 ボタンのときに次に止めるリール（回転中で停止要求の出ていない一番左）を返す。無ければ -1。
func (g *slotgame_game) nextReel() int {
	for i := range g.reels {
		if g.reels[i].spinning && !g.reels[i].stopping {
			return i
		}
	}
	return -1
}

func (g *slotgame_game) finishSpin() {
	win, msg := slotgame_judge(g.reels[0].center(), g.reels[1].center(), g.reels[2].center())
	g.credit += win
	g.drawCredit()
	switch {
	case g.credit < slotgame_bet:
		g.drawMessage(g.lay.gameOver, slotgame_colRed)
		g.state = slotgame_stateGameOver
	case win > 0:
		g.drawMessage(msg, slotgame_colYellow)
		g.state = slotgame_stateIdle
	default:
		g.drawMessage(msg, slotgame_colWhite)
		g.state = slotgame_stateIdle
	}
}

// ---- 画面描画 ----

func (g *slotgame_game) drawStatic() {
	s, l := g.scr, &g.lay
	s.FillRectangle(0, 0, l.screenW, slotgame_screenH, slotgame_colBG)
	tinyfont.WriteLine(s, &freesans.Bold12pt7b, 8, 26, "SLOT", slotgame_colYellow)
	w := int16(l.symW)
	for _, x := range l.reelX {
		g.drawFrame(x-1, slotgame_reelY-1, w+2, slotgame_reelH+2)
		g.drawFrame(x-2, slotgame_reelY-2, w+4, slotgame_reelH+4)
	}
	// 有効ラインを指す内向きの三角マーカー
	for i := int16(0); i < l.markerW; i++ {
		h := l.markerW - 1 - i
		s.FillRectangle(l.markerX+i, slotgame_markerCY-h, 1, 2*h+1, slotgame_colLine)
		s.FillRectangle(l.screenW-1-l.markerX-i, slotgame_markerCY-h, 1, 2*h+1, slotgame_colLine)
	}
}

// drawFrame は 1px の枠を描く。
func (g *slotgame_game) drawFrame(x, y, w, h int16) {
	s := g.scr
	s.FillRectangle(x, y, w, 1, slotgame_colFrame)
	s.FillRectangle(x, y+h-1, w, 1, slotgame_colFrame)
	s.FillRectangle(x, y, 1, h, slotgame_colFrame)
	s.FillRectangle(x+w-1, y, 1, h, slotgame_colFrame)
}

func (g *slotgame_game) drawCredit() {
	s, sw := g.scr, g.lay.screenW
	// 右寄せの「CREDIT n」を消す範囲。左の「SLOT」にはかからないようにする。
	_, tw := tinyfont.LineWidth(&freesans.Bold12pt7b, "SLOT")
	x := max(sw-170, 8+int16(tw)+4)
	s.FillRectangle(x, 4, sw-x, 30, slotgame_colBG)
	str := "CREDIT " + strconv.Itoa(g.credit)
	_, w := tinyfont.LineWidth(&freesans.Bold12pt7b, str)
	tinyfont.WriteLine(s, &freesans.Bold12pt7b, sw-8-int16(w), 26, str, slotgame_colWhite)
}

func (g *slotgame_game) clearMessage() {
	g.scr.FillRectangle(0, slotgame_msgY, g.lay.screenW, slotgame_msgH, slotgame_colBG)
}

func (g *slotgame_game) drawMessage(msg string, col color.RGBA) {
	g.clearMessage()
	_, w := tinyfont.LineWidth(&freesans.Bold9pt7b, msg)
	tinyfont.WriteLine(g.scr, &freesans.Bold9pt7b, (g.lay.screenW-int16(w))/2, 213, msg, col)
}

func (g *slotgame_game) drawReel(i int) {
	g.reels[i].render(g.reelImg, &g.syms)
	g.scr.DrawBitmap(g.lay.reelX[i], slotgame_reelY, g.reelImg)
}

func (g *slotgame_game) drawLabels() {
	for i := range g.reels {
		g.drawLabel(i)
	}
}

// drawLabel は SW1 ラベルを描く。回転中は赤、停止中は灰。
// 1 ボタンのときは、次に止まるリールだけを赤にし、順番待ちのリールは暗い赤、
// 停止要求を出したリールは灰にする。
func (g *slotgame_game) drawLabel(i int) {
	bg, fg := slotgame_colGray, slotgame_colBG
	switch r := &g.reels[i]; {
	case !r.spinning, g.oneButton && r.stopping:
	case g.oneButton && i != g.nextReel():
		bg, fg = slotgame_colDarkRed, slotgame_colGray
	default:
		bg, fg = slotgame_colRed, slotgame_colWhite
	}
	x, w := g.lay.reelX[i], int16(g.lay.symW)
	g.scr.FillRectangle(x, slotgame_labelY, w, slotgame_labelH, bg)
	const label = "SW1"
	_, tw := tinyfont.LineWidth(&freesans.Bold9pt7b, label)
	tinyfont.WriteLine(g.scr, &freesans.Bold9pt7b, x+(w-int16(tw))/2, 236, label, fg)
}
