// Code generated by go generate; DO NOT EDIT.
// Source: ../selftest/main.go
// Launcher input adaptations are defined in generate.go.

// 基板上の全デバイスを一度に動作確認するセルフテスト。
// 組み立てた基板の検査や、ワークショップ前の動作確認に使う。
//
// 起動直後にジョイスティックのセンター位置を測るので、電源投入・リセット直後は
// スティックに触らないこと。そのあと LCD を赤・緑・青の順に全面表示し
// (ドット欠けや色の確認)、起動音を鳴らしてテスト画面になる。
// テスト画面では各項目を次のように確認する。
//
//	SW1 / SW2   押すと緑になる。押すたびにビープ音が鳴る (スピーカーの確認)
//	JOY         ボタンを押す、スティックを上下左右いっぱいに倒すと U D L R が緑になる。
//	            右上の枠にスティックの位置を表示する
//	LED         WS2812B 2 個が赤、緑、青、白の順に変わる。画面の色見本と同じか目で見る
//	AHT21B      温湿度を 1 秒ごとに読む。読めて値が妥当なら緑
//	GROVE       Grove コネクタの I2C バスを 2 秒ごとにスキャンし、応答したアドレスを表示
//	            (何もつないでいなければ none。合否には含めない)
//	IR          1 秒ごとに NEC フォーマットで送信し、反射光を自分で受信できたら緑。
//	            表示は「自己受信できた回数/送信回数」。返ってこないときは白い紙などを
//	            赤外線 LED と受信モジュールの前にかざす。ほかのリモコンの信号を受けたら
//	            ext にアドレス:コマンド を表示する
//	AUDIO       I2S の初期化に成功したら緑。音が出ているかは耳で確認する
//
// 自動で判定できる項目 (SW1, SW2, JOY, AHT21B, IR, AUDIO) がすべて緑になると
// 最下行が ALL OK になる。LCD, LED, スピーカー, Grove は目と耳で確認する。
// 判定結果や受信データはシリアルにも出力する。
package main

import (
	"image/color"
	"runtime/volatile"
	"time"

	"tinygo.org/x/drivers/irremote"
	"tinygo.org/x/tinyfont"
	"tinygo.org/x/tinyfont/freesans"

	"github.com/sago35/tinygo-conf-2026-badge/firmware/badge"
)

var (
	selftest_black  = color.RGBA{0, 0, 0, 255}
	selftest_white  = color.RGBA{255, 255, 255, 255}
	selftest_gray   = color.RGBA{64, 64, 64, 255}
	selftest_green  = color.RGBA{0, 255, 0, 255}
	selftest_red    = color.RGBA{255, 0, 0, 255}
	selftest_blue   = color.RGBA{0, 0, 255, 255}
	selftest_yellow = color.RGBA{255, 220, 0, 255}
	selftest_cyan   = color.RGBA{0, 255, 255, 255}
)

var selftest_font = &freesans.Regular9pt7b

// 画面のレイアウト。1 行 22 ドット (freesans 9pt の行送り)。
const (
	selftest_labelX  = 4
	selftest_valueX  = 70
	selftest_rowH    = 22
	selftest_firstY  = 42 // 最初の項目行のベースライン
	selftest_padSize = 64 // ジョイスティック表示の枠
	selftest_padX    = badge.LCD_WIDTH - selftest_padSize - 6
	selftest_padY    = 26
)

// 音量 (0..255)。examples/audio と同じ。
const selftest_volume = 32

// 赤外線の送信アドレス。コマンドは送るたびに 1 ずつ増やす。
const selftest_irAddress = 0x10

// LED の点灯パターン。ledInterval ごとに次の色に進む。
var selftest_ledColors = []struct {
	name string
	c    color.RGBA
}{
	{"red", selftest_red},
	{"green", selftest_green},
	{"blue", selftest_blue},
	{"white", selftest_white},
}

const selftest_ledInterval = 500 * time.Millisecond

// 赤外線受信の割り込みからメインループへの受け渡し用 (examples/ir と同じ)。
// 割り込み内で println すると USB シリアルが止まることがあるので、保存だけする。
var (
	selftest_rxSeq     volatile.Register32
	selftest_rxCode    volatile.Register32
	selftest_rxAddress volatile.Register16
	selftest_rxCommand volatile.Register16
	selftest_rxFlags   volatile.Register16
)

func selftest_onReceive(d irremote.Data) {
	selftest_rxCode.Set(d.Code)
	selftest_rxAddress.Set(d.Address)
	selftest_rxCommand.Set(d.Command)
	selftest_rxFlags.Set(uint16(d.Flags))
	selftest_rxSeq.Set(selftest_rxSeq.Get() + 1)
}

// check は自動判定する項目。一度 OK になったら OK のまま。
type selftest_check struct {
	name string
	ok   bool
}

func (c *selftest_check) pass() {
	if !c.ok {
		c.ok = true
		println("PASS", c.name)
	}
}

func selftest_main() {
	// ジョイスティックのセンター位置は起動直後に測る (触らないこと)
	joy := badge.NewJoystick()
	joy.Calibrate(300 * time.Millisecond)

	time.Sleep(200 * time.Millisecond)
	println("selftest start, id", badge.SerialNumber())

	display := badge.NewDisplay()
	fb := badge.NewFramebuffer(display)
	w, h := fb.Size()

	// LCD の全面表示。この間にほかのデバイスを初期化する
	fb.FillScreen(selftest_red)
	fb.Display()
	leds := badge.NewLEDs()
	leds.SetBrightness(32)
	sw1, sw2 := badge.NewButtons()
	time.Sleep(300 * time.Millisecond)

	fb.FillScreen(selftest_green)
	fb.Display()
	sensor := badge.NewSensor()
	badge.ConfigureGroveI2C()
	rx := badge.NewIRReceiver()
	rx.SetCommandHandler(selftest_onReceive)
	tx, txErr := badge.NewIRTransmitter()
	if txErr != nil {
		println("ir tx init:", txErr.Error())
	}
	time.Sleep(300 * time.Millisecond)

	fb.FillScreen(selftest_blue)
	fb.Display()
	time.Sleep(300 * time.Millisecond)

	var (
		chkSW1   = selftest_check{name: "SW1"}
		chkSW2   = selftest_check{name: "SW2"}
		chkBtn   = selftest_check{name: "JOY button"}
		chkUp    = selftest_check{name: "JOY up"}
		chkDown  = selftest_check{name: "JOY down"}
		chkLeft  = selftest_check{name: "JOY left"}
		chkRight = selftest_check{name: "JOY right"}
		chkAHT   = selftest_check{name: "AHT21B"}
		chkIR    = selftest_check{name: "IR loopback"}
		chkAudio = selftest_check{name: "AUDIO"}
	)
	checks := []*selftest_check{&chkSW1, &chkSW2, &chkBtn, &chkUp, &chkDown, &chkLeft, &chkRight, &chkAHT, &chkIR, &chkAudio}

	audio, audioErr := badge.NewAudio()
	var tone *badge.ToneGenerator
	if audioErr != nil {
		println("audio init:", audioErr.Error())
	} else {
		chkAudio.pass()
		tone = badge.NewToneGenerator(audio)
		for _, n := range []uint32{523, 659, 784} {
			tone.Play(n, 80, selftest_volume)
		}
		tone.Stop()
	}
	beep := func(freq uint32) {
		if tone != nil {
			tone.Play(freq, 60, selftest_volume)
			tone.Stop()
		}
	}

	ledIdx := 0
	lastLED := time.Time{}

	lastSensor := time.Time{}
	sensorText := "reading..."

	lastScan := time.Time{}
	groveText := "scanning..."
	groveColor := selftest_yellow

	lastTX := time.Time{}
	irCmd := uint8(0)
	irSent := 0
	irBack := 0
	irOther := "" // 自分以外から受信したコード
	lastSeq := selftest_rxSeq.Get()

	prev1, prev2, prevBtn := false, false, false
	allOK := false

	for {
		frameStart := time.Now()
		now := frameStart

		// ---- 入力 ----
		x, y, btn := joy.Read()
		p1, p2 := sw1.Pressed(), sw2.Pressed()
		if p1 {
			chkSW1.pass()
		}
		if p2 {
			chkSW2.pass()
		}
		if btn {
			chkBtn.pass()
		}
		const edge = 900
		if y > edge {
			chkUp.pass()
		}
		if y < -edge {
			chkDown.pass()
		}
		if x < -edge {
			chkLeft.pass()
		}
		if x > edge {
			chkRight.pass()
		}

		// 押した瞬間にビープを鳴らす (ボタンごとに音程を変える)
		if p1 && !prev1 {
			beep(880)
		}
		if p2 && !prev2 {
			beep(660)
		}
		if btn && !prevBtn {
			beep(440)
		}
		prev1, prev2, prevBtn = p1, p2, btn

		// ---- LED ----
		if now.Sub(lastLED) >= selftest_ledInterval {
			lastLED = now
			ledIdx = (ledIdx + 1) % len(selftest_ledColors)
			c := selftest_ledColors[ledIdx].c
			leds.WriteColors([]color.RGBA{c, c})
		}

		// ---- 温湿度センサー ----
		if now.Sub(lastSensor) >= time.Second {
			lastSensor = now
			if err := sensor.Read(); err != nil {
				sensorText = "read error"
			} else {
				t, rh := sensor.DeciCelsius(), sensor.DeciRelHumidity()
				sensorText = selftest_deci(t) + "C " + selftest_deci(rh) + "%"
				if t > -200 && t < 800 && rh > 0 && rh <= 1000 {
					chkAHT.pass()
				} else {
					sensorText += " ?"
				}
			}
		}

		// ---- Grove I2C ----
		if now.Sub(lastScan) >= 2*time.Second {
			lastScan = now
			found := badge.ScanI2C(badge.GroveI2C)
			s := ""
			for _, addr := range found {
				s += "0x" + selftest_hex8(uint8(addr)) + " "
			}
			if s == "" {
				s = "none"
				groveColor = selftest_white
			} else {
				groveColor = selftest_cyan
			}
			if s != groveText {
				println("grove i2c:", s)
			}
			groveText = s
		}

		// ---- 赤外線 ----
		if seq := selftest_rxSeq.Get(); seq != lastSeq {
			lastSeq = seq
			repeat := selftest_rxFlags.Get()&uint16(irremote.DataFlagIsRepeat) != 0
			addr, cmd := selftest_rxAddress.Get(), selftest_rxCommand.Get()
			if !repeat && addr == selftest_irAddress && cmd == uint16(irCmd) {
				irBack++
				chkIR.pass()
			} else if !repeat {
				irOther = selftest_hex8(uint8(addr)) + ":" + selftest_hex8(uint8(cmd))
				println("ir rx: addr", addr, "cmd", cmd, "code 0x"+selftest_hex32(selftest_rxCode.Get()))
			}
		}
		if tx != nil && now.Sub(lastTX) >= time.Second {
			lastTX = now
			irCmd++
			irSent++
			tx.SendNEC(selftest_irAddress, irCmd)
		}

		// ---- 判定 ----
		if !allOK {
			allOK = true
			for _, c := range checks {
				allOK = allOK && c.ok
			}
			if allOK {
				println("ALL OK")
				if tone != nil {
					for _, n := range []uint32{784, 1047} {
						tone.Play(n, 100, selftest_volume)
					}
					tone.Stop()
				}
			}
		}

		// ---- 描画 ----
		fb.FillScreen(selftest_black)
		tinyfont.WriteLine(fb, selftest_font, selftest_labelX, 18, "SELF TEST #"+badge.SerialNumber(), selftest_white)

		row := int16(selftest_firstY)
		label := func(s string) {
			tinyfont.WriteLine(fb, selftest_font, selftest_labelX, row, s, selftest_white)
		}

		label("SW1")
		selftest_text(fb, selftest_valueX, row, selftest_pressedText(p1), selftest_state(chkSW1.ok))
		row += selftest_rowH

		label("SW2")
		selftest_text(fb, selftest_valueX, row, selftest_pressedText(p2), selftest_state(chkSW2.ok))
		row += selftest_rowH

		label("JOY")
		cx := selftest_text(fb, selftest_valueX, row, "B", selftest_state(chkBtn.ok))
		cx = selftest_text(fb, cx+6, row, "U", selftest_state(chkUp.ok))
		cx = selftest_text(fb, cx+6, row, "D", selftest_state(chkDown.ok))
		cx = selftest_text(fb, cx+6, row, "L", selftest_state(chkLeft.ok))
		selftest_text(fb, cx+6, row, "R", selftest_state(chkRight.ok))
		row += selftest_rowH

		label("LED")
		lc := selftest_ledColors[ledIdx]
		fb.FillRectangle(selftest_valueX, row-13, 24, 14, lc.c)
		selftest_text(fb, selftest_valueX+30, row, lc.name, selftest_white)
		row += selftest_rowH

		label("AHT")
		selftest_text(fb, selftest_valueX, row, sensorText, selftest_state(chkAHT.ok))
		row += selftest_rowH

		label("GROVE")
		selftest_text(fb, selftest_valueX, row, groveText, groveColor)
		row += selftest_rowH

		label("IR")
		irText := selftest_itoa(irBack) + "/" + selftest_itoa(irSent)
		if tx == nil {
			irText = "tx init error"
		}
		cx = selftest_text(fb, selftest_valueX, row, irText, selftest_state(chkIR.ok))
		if irOther != "" {
			selftest_text(fb, cx+8, row, "ext "+irOther, selftest_cyan)
		}
		row += selftest_rowH

		label("AUDIO")
		if audioErr != nil {
			selftest_text(fb, selftest_valueX, row, "init error", selftest_red)
		} else {
			selftest_text(fb, selftest_valueX, row, "ok (listen)", selftest_green)
		}

		// ジョイスティックの位置
		fb.FillRectangle(selftest_padX, selftest_padY, selftest_padSize, selftest_padSize, selftest_gray)
		fb.FillRectangle(selftest_padX+selftest_padSize/2, selftest_padY, 1, selftest_padSize, selftest_black)
		fb.FillRectangle(selftest_padX, selftest_padY+selftest_padSize/2, selftest_padSize, 1, selftest_black)
		nx := selftest_padX + int16((x+1000)*(selftest_padSize-6)/2000)
		ny := selftest_padY + int16((1000-y)*(selftest_padSize-6)/2000)
		dot := selftest_white
		if btn {
			dot = selftest_red
		}
		fb.FillRectangle(nx, ny, 6, 6, dot)

		// 最下行に総合判定
		if allOK {
			fb.FillRectangle(0, h-24, w, 24, selftest_green)
			selftest_text(fb, selftest_labelX, h-6, "ALL OK", selftest_black)
		} else {
			left := 0
			for _, c := range checks {
				if !c.ok {
					left++
				}
			}
			selftest_text(fb, selftest_labelX, h-6, selftest_itoa(left)+" check(s) left", selftest_yellow)
		}
		fb.Display()

		// 約 30fps に揃える
		if d := 33*time.Millisecond - time.Since(frameStart); d > 0 {
			time.Sleep(d)
		}
	}
}

// text は (x, y) に文字列を描き、描いた文字列の右端の x を返す。
func selftest_text(fb *badge.Framebuffer, x, y int16, s string, c color.RGBA) int16 {
	tinyfont.WriteLine(fb, selftest_font, x, y, s, c)
	_, width := tinyfont.LineWidth(selftest_font, s)
	return x + int16(width)
}

// state は判定済みなら緑、未確認なら黄色を返す。
func selftest_state(ok bool) color.RGBA {
	if ok {
		return selftest_green
	}
	return selftest_yellow
}

func selftest_pressedText(p bool) string {
	if p {
		return "pressed"
	}
	return "-"
}

// deci は 1/10 単位の整数を "12.3" 形式の文字列にする。
func selftest_deci(v int32) string {
	neg := v < 0
	if neg {
		v = -v
	}
	s := selftest_itoa(int(v/10)) + "." + selftest_itoa(int(v%10))
	if neg {
		return "-" + s
	}
	return s
}

func selftest_itoa(v int) string {
	if v == 0 {
		return "0"
	}
	var buf [12]byte
	i := len(buf)
	for v > 0 {
		i--
		buf[i] = byte('0' + v%10)
		v /= 10
	}
	return string(buf[i:])
}

const selftest_hexDigits = "0123456789abcdef"

func selftest_hex8(v uint8) string {
	return string([]byte{selftest_hexDigits[v>>4], selftest_hexDigits[v&0xf]})
}

func selftest_hex32(v uint32) string {
	var b [8]byte
	for i := range b {
		b[i] = selftest_hexDigits[v>>(28-4*i)&0xf]
	}
	return string(b[:])
}
