// Code generated by go generate; DO NOT EDIT.
// Source: ../rhythm/effects.go

package main

import (
	"image/color"
	"time"

	"tinygo.org/x/tinyfont"
	"tinygo.org/x/tinyfont/freesans"

	"github.com/sago35/tinygo-conf-2026-badge/firmware/badge"
)

// コンボ (GOOD 以上の連続) が続いているときの演出。コンボ数に応じて段階的に増える。
//
//	1 以上   ヒットした位置から火花が飛ぶ (コンボが多いほど数が増える)
//	10 以上  判定ラインが拍に合わせて脈打つ。背景にコンボ数を大きく薄く表示
//	30 以上  背景を星が流れ上がる。判定ラインが虹色になる
//	50 以上  画面の縁が拍に合わせて虹色に光る
//	10 の倍数ごとに「20 COMBO!」を大きく表示して、虹色の火花を散らす
//
// 10 コンボ以上で MISS すると、画面の縁が一瞬赤く光る (COMBO BREAK)。
const (
	rhythm_comboTier1 = 10
	rhythm_comboTier2 = 30
	rhythm_comboTier3 = 50
)

var rhythm_fontHuge = &freesans.Bold24pt7b

// particle は火花 1 個。位置と速度は 1/16 ドット単位。
type rhythm_particle struct {
	x, y, vx, vy int32
	c            color.RGBA
	life         int // 残りフレーム数
}

const rhythm_maxParticles = 64

type rhythm_effects struct {
	parts [rhythm_maxParticles]rhythm_particle
	rng   uint32

	milestone   int           // 直近に達成した 10 の倍数のコンボ数
	milestoneAt time.Duration // その時刻
	breakAt     time.Duration // COMBO BREAK の時刻
}

func rhythm_newEffects() *rhythm_effects {
	return &rhythm_effects{rng: 0x12345678, milestoneAt: -time.Hour, breakAt: -time.Hour}
}

func (e *rhythm_effects) rand(n int) int {
	// xorshift32
	e.rng ^= e.rng << 13
	e.rng ^= e.rng >> 17
	e.rng ^= e.rng << 5
	return int(e.rng % uint32(n))
}

// spawn は (x, y) から上向きに火花を n 個飛ばす。c が nil なら虹色。
func (e *rhythm_effects) spawn(x, y int16, n int, c *color.RGBA) {
	for k := 0; k < n; k++ {
		// 空いている (寿命が尽きた) 枠を探す。無ければ諦める
		var p *rhythm_particle
		for i := range e.parts {
			if e.parts[i].life <= 0 {
				p = &e.parts[i]
				break
			}
		}
		if p == nil {
			return
		}
		pc := rhythm_hue(e.rand(1536))
		if c != nil {
			pc = *c
		}
		*p = rhythm_particle{
			x:    int32(x) * 16,
			y:    int32(y) * 16,
			vx:   int32(e.rand(97) - 48),
			vy:   -int32(32 + e.rand(64)),
			c:    pc,
			life: 10 + e.rand(10),
		}
	}
}

// hit はノーツをヒットしたときに呼ぶ。combo はヒット後のコンボ数。
func (e *rhythm_effects) hit(lane, combo int, now time.Duration) {
	x := int16(lane*rhythm_laneW + rhythm_laneW/2)
	c := rhythm_laneColors[lane]
	n := 3 + combo/10*2
	if n > 12 {
		n = 12
	}
	e.spawn(x, rhythm_judgeY, n, &c)
	if combo > 0 && combo%10 == 0 {
		e.milestone = combo
		e.milestoneAt = now
		e.spawn(badge.LCD_WIDTH/2, 100, 24, nil)
	}
}

// miss は MISS したときに呼ぶ。prevCombo は MISS の直前のコンボ数。
func (e *rhythm_effects) miss(prevCombo int, now time.Duration) {
	if prevCombo >= rhythm_comboTier1 {
		e.breakAt = now
	}
}

// update は 1 フレームごとに火花を動かす。
func (e *rhythm_effects) update() {
	for i := range e.parts {
		p := &e.parts[i]
		if p.life <= 0 {
			continue
		}
		p.x += p.vx
		p.y += p.vy
		p.vy += 6 // 重力
		p.life--
	}
}

// beatPulse は拍の頭で 255、次の拍に向けて 0 まで下がる値を返す。
func rhythm_beatPulse(now time.Duration) int {
	if now < 0 {
		return 0
	}
	const beat = 2 * rhythm_stepMs * time.Millisecond // 4 分音符
	return 255 - int((now%beat)*255/beat)
}

// drawBack はノーツより後ろに描く演出 (背景の星、大きなコンボ数)。
func (e *rhythm_effects) drawBack(fb *badge.Framebuffer, now time.Duration, combo int) {
	if combo >= rhythm_comboTier2 {
		// 星はフレーム間で状態を持たず、番号と時刻から位置を決める
		ms := int(now / time.Millisecond)
		const span = rhythm_judgeY - rhythm_topMargin
		for i := 0; i < 24; i++ {
			h := uint32(i)*2654435761 + 12345
			x := int16(h % badge.LCD_WIDTH)
			speed := 40 + int(h>>8%80) // ドット/秒
			y := rhythm_judgeY - int16((int(h>>16)+ms*speed/1000)%span)
			fb.FillRectangle(x, y, 2, 2, rhythm_scale(rhythm_hue(int(h>>4%1536)), 110))
		}
	}
	if combo >= rhythm_comboTier1 {
		s := rhythm_itoa(combo)
		_, w := tinyfont.LineWidth(rhythm_fontHuge, s)
		c := color.RGBA{40, 40, 60, 255}
		if combo >= rhythm_comboTier2 {
			c = rhythm_scale(rhythm_hue(int(now/time.Millisecond)%1536), 60)
		}
		tinyfont.WriteLine(fb, rhythm_fontHuge, (badge.LCD_WIDTH-int16(w))/2, 160, s, c)
	}
}

// judgeLine は判定ラインを描く。10 コンボ以上で拍に合わせて太くなる。
func (e *rhythm_effects) judgeLine(fb *badge.Framebuffer, now time.Duration, combo int) {
	if combo < rhythm_comboTier1 {
		fb.FillRectangle(0, rhythm_judgeY, badge.LCD_WIDTH, 2, rhythm_white)
		return
	}
	pulse := rhythm_beatPulse(now)
	extra := int16(pulse * 3 / 255) // 0..3 ドット太くする
	if combo >= rhythm_comboTier2 {
		// 虹色が左から右へ流れる
		base := int(now / time.Millisecond)
		for x := int16(0); x < badge.LCD_WIDTH; x += 8 {
			c := rhythm_hue((base + int(x)*6) % 1536)
			fb.FillRectangle(x, rhythm_judgeY-extra, 8, 2+2*extra, c)
		}
		return
	}
	fb.FillRectangle(0, rhythm_judgeY-extra, badge.LCD_WIDTH, 2+2*extra, rhythm_scale(rhythm_yellow, 128+pulse/2))
}

// drawFront はノーツより手前に描く演出 (火花、縁の光、達成表示)。
func (e *rhythm_effects) drawFront(fb *badge.Framebuffer, now time.Duration, combo int) {
	for i := range e.parts {
		p := &e.parts[i]
		if p.life <= 0 {
			continue
		}
		size := int16(2)
		if p.life > 8 {
			size = 3
		}
		fb.FillRectangle(int16(p.x/16), int16(p.y/16), size, size, p.c)
	}

	// 画面の縁 (スコア表示の下からラベルの上まで)
	if combo >= rhythm_comboTier3 {
		pulse := rhythm_beatPulse(now)
		if pulse > 64 {
			c := rhythm_scale(rhythm_hue(int(now/time.Millisecond)*2%1536), pulse)
			rhythm_border(fb, 3, c)
		}
	}
	if d := now - e.breakAt; d < 300*time.Millisecond {
		rhythm_border(fb, 4, rhythm_scale(rhythm_red, 255-int(d*255/(300*time.Millisecond))))
	}

	// 10 コンボごとの達成表示 (0.8 秒)
	if d := now - e.milestoneAt; d < 800*time.Millisecond {
		c := rhythm_hue(int(d/time.Millisecond) * 6 % 1536)
		rhythm_centerText(rhythm_fontBold, 92, rhythm_itoa(e.milestone)+" COMBO!", c)
	}
}

// border はプレイエリアの縁を太さ t で塗る。
func rhythm_border(fb *badge.Framebuffer, t int16, c color.RGBA) {
	const top, bottom = rhythm_topMargin, rhythm_judgeY + 2
	fb.FillRectangle(0, top, badge.LCD_WIDTH, t, c)
	fb.FillRectangle(0, bottom-t, badge.LCD_WIDTH, t, c)
	fb.FillRectangle(0, top, t, bottom-top, c)
	fb.FillRectangle(badge.LCD_WIDTH-t, top, t, bottom-top, c)
}

// hue は色相 h (0..1535) の鮮やかな色を返す。
func rhythm_hue(h int) color.RGBA {
	v := uint8(h % 256)
	switch h / 256 % 6 {
	case 0:
		return color.RGBA{255, v, 0, 255}
	case 1:
		return color.RGBA{255 - v, 255, 0, 255}
	case 2:
		return color.RGBA{0, 255, v, 255}
	case 3:
		return color.RGBA{0, 255 - v, 255, 255}
	case 4:
		return color.RGBA{v, 0, 255, 255}
	default:
		return color.RGBA{255, 0, 255 - v, 255}
	}
}
