// Code generated by go generate; DO NOT EDIT.
// Source: ../audiotest/main.go
// Launcher input adaptations are defined in generate.go.

// I2S (MAX98357) の動作確認用。ロジアナやスピーカーで波形を見るために
// 1kHz の正弦波を鳴らし続ける。
//   - 起動 2 秒後にレジスタと各ピンのトグル状況を診断出力する
//   - その後は 1kHz を鳴らし続ける
//   - SW1 を押している間は 440Hz に切り替わる
//   - SW2 を押している間は無音になる
//
// 期待値: BCLK 512kHz、LRC 16kHz、DIN は 16bit MSB first。
// アンプの + / − には約 300kHz のパルスが出て、差分に正弦波が乗る。
package main

import (
	"time"

	"github.com/sago35/tinygo-conf-2026-badge/firmware/badge"
)

const audiotest_volume = 64 // 0..255

func audiotest_main() {
	time.Sleep(2 * time.Second)
	sw1, sw2 := badge.NewButtons()

	audio, err := badge.NewAudio()
	if err != nil {
		println("audio init:", err.Error())
		select {}
	}
	tone := badge.NewToneGenerator(audio)
	println("audio ready")

	// 診断: レジスタの状態と、各ピンが実際にトグルしているか
	time.Sleep(100 * time.Millisecond)
	audio.DumpRegisters()
	b, l, d := audio.CountToggles(20000)
	println("toggles in 20000 reads: BCLK", b, "LRC", l, "DIN", d)

	println("playing 1kHz sine (SW1: 440Hz, SW2: mute)")
	silent := false
	for {
		switch {
		case sw2.Pressed():
			if !silent {
				tone.Stop()
				silent = true
			}
			time.Sleep(10 * time.Millisecond)
			continue
		case sw1.Pressed():
			err = tone.Hold(440, 50, audiotest_volume)
		default:
			err = tone.Hold(1000, 50, audiotest_volume)
		}
		silent = false
		if err != nil {
			println("play:", err.Error())
			audio.DumpRegisters()
			time.Sleep(time.Second)
		}
	}
}
