// Code generated by go generate; DO NOT EDIT.
// Source: ../ble-scanner/main.go
// Launcher input adaptations are defined in generate.go.

// BLE で周囲のデバイスをスキャンし、アドレス、RSSI、名前をシリアルに出力する。
// 同じアドレスは 1 回だけ表示する (RSSI の更新は表示しない)。
//
//	CGO_CFLAGS_ALLOW=-fno-short-enums tinygo flash --target esp32s3-box-3 --size short ./examples/ble-scanner
//
// TinyGo 0.43 より古い場合は firmware/README.md の BLE の手順を参照。
package main

import (
	"time"

	"tinygo.org/x/bluetooth"
)

var ble_scanner_adapter = bluetooth.DefaultAdapter

// 表示済みのアドレス
var ble_scanner_seen [64]bluetooth.Address
var ble_scanner_seenCount int

func ble_scanner_main() {
	time.Sleep(2 * time.Second)
	println("enabling BLE...")
	ble_scanner_must("enable BLE stack", ble_scanner_adapter.Enable())

	println("scanning (address / RSSI / name)...")
	ble_scanner_must("scan", ble_scanner_adapter.Scan(func(a *bluetooth.Adapter, dev bluetooth.ScanResult) {
		for i := 0; i < ble_scanner_seenCount; i++ {
			if ble_scanner_seen[i] == dev.Address {
				return
			}
		}
		if ble_scanner_seenCount < len(ble_scanner_seen) {
			ble_scanner_seen[ble_scanner_seenCount] = dev.Address
			ble_scanner_seenCount++
		}
		println(dev.Address.String(), dev.RSSI, dev.LocalName())
	}))
}

func ble_scanner_must(action string, err error) {
	for err != nil {
		println("failed to " + action + ": " + err.Error())
		time.Sleep(time.Second)
	}
}
