// Code generated by go generate; DO NOT EDIT.
// Source: ../demo/main.go

// バッジの全機能デモ。
//   - LCD にジョイスティック位置、ボタン状態、温湿度を表示
//   - ジョイスティックの位置に応じて WS2812B の色が変わる
//   - SW1 / SW2 で LED の明るさを変える
//
// 描画はフレームバッファ (badge.Framebuffer) に行い、1 フレーム分をまとめて
// LCD に転送する。ディスプレイに直接描くと部分ごとの書き換えが見えてちらつく。
package main

import (
	"image/color"
	"time"

	"tinygo.org/x/tinyfont"
	"tinygo.org/x/tinyfont/freesans"

	"github.com/sago35/tinygo-conf-2026-badge/firmware/badge"
)

var (
	demo_black = color.RGBA{0, 0, 0, 255}
	demo_white = color.RGBA{255, 255, 255, 255}
	demo_gray  = color.RGBA{64, 64, 64, 255}
	demo_green = color.RGBA{0, 255, 0, 255}
	demo_red   = color.RGBA{255, 0, 0, 255}
)

func demo_main() {
	display := badge.NewDisplay()
	fb := badge.NewFramebuffer(display)
	leds := badge.NewLEDs()
	sw1, sw2 := badge.NewButtons()
	joy := badge.NewJoystick()
	joy.Calibrate(300 * time.Millisecond)
	time.Sleep(100 * time.Millisecond)
	sensor := badge.NewSensor()

	w, h := fb.Size()

	// ジョイスティック表示エリア (中央の四角)
	const padSize = 100
	padX := (w - padSize) / 2
	padY := int16(40)

	brightness := uint8(32)
	colors := make([]color.RGBA, badge.WS2812_COUNT)
	lastSensor := time.Time{}
	sensorText := "reading..."
	sensorColor := demo_white
	prevSW1, prevSW2 := false, false

	for {
		frameStart := time.Now()
		x, y, btn := joy.Read()
		p1, p2 := sw1.Pressed(), sw2.Pressed()

		// ボタンで LED の明るさを調整
		if p1 && !prevSW1 && brightness < 224 {
			brightness += 32
		}
		if p2 && !prevSW2 && brightness > 32 {
			brightness -= 32
		}
		prevSW1, prevSW2 = p1, p2
		leds.SetBrightness(brightness)

		// ジョイスティックの位置を LED の色に反映
		c := color.RGBA{R: uint8((x + 1000) / 8), G: uint8((y + 1000) / 8), B: 0, A: 255}
		if btn {
			c.B = 255
		}
		for i := range colors {
			colors[i] = c
		}
		leds.WriteColors(colors)

		// 温湿度は 1 秒ごとに読む
		if time.Since(lastSensor) > time.Second {
			lastSensor = time.Now()
			if err := sensor.Read(); err == nil {
				sensorText = demo_deci(sensor.DeciCelsius()) + "C  " + demo_deci(sensor.DeciRelHumidity()) + "%"
				sensorColor = demo_white
			} else {
				sensorText = "sensor error"
				sensorColor = demo_red
			}
		}

		// 1 フレーム分をフレームバッファに描いてから一括転送
		fb.FillScreen(demo_black)
		tinyfont.WriteLine(fb, &freesans.Bold12pt7b, 8, 24, "TinyGo Conf 2026", demo_white)
		fb.FillRectangle(padX, padY, padSize, padSize, demo_gray)
		// 中心線
		fb.FillRectangle(padX+padSize/2, padY, 1, padSize, demo_black)
		fb.FillRectangle(padX, padY+padSize/2, padSize, 1, demo_black)
		// ジョイスティックの位置 (8x8 のドット)
		nx := padX + int16((x+1000)*(padSize-8)/2000)
		ny := padY + int16((1000-y)*(padSize-8)/2000)
		dotColor := demo_white
		if btn {
			dotColor = demo_red
		}
		fb.FillRectangle(nx, ny, 8, 8, dotColor)
		tinyfont.WriteLine(fb, &freesans.Regular9pt7b, 8, padY+padSize+26,
			"SW1:"+demo_onoff(p1)+" SW2:"+demo_onoff(p2)+" JOY:"+demo_onoff(btn), demo_green)
		tinyfont.WriteLine(fb, &freesans.Regular9pt7b, 8, h-12, sensorText, sensorColor)
		fb.Display()

		// 約 30fps に揃える
		if d := 33*time.Millisecond - time.Since(frameStart); d > 0 {
			time.Sleep(d)
		}
	}
}

func demo_onoff(b bool) string {
	if b {
		return "ON "
	}
	return "off"
}

// deci は 1/10 単位の整数を "12.3" 形式の文字列にする。
func demo_deci(v int32) string {
	neg := v < 0
	if neg {
		v = -v
	}
	s := demo_itoa(int(v/10)) + "." + demo_itoa(int(v%10))
	if neg {
		return "-" + s
	}
	return s
}

func demo_itoa(v int) string {
	if v == 0 {
		return "0"
	}
	var buf [12]byte
	i := len(buf)
	for v > 0 {
		i--
		buf[i] = byte('0' + v%10)
		v /= 10
	}
	return string(buf[i:])
}
