// Code generated by go generate; DO NOT EDIT.
// Source: ../input/main.go
// Launcher input adaptations are defined in generate.go.

// ボタン (SW1/SW2) とジョイスティックの状態をシリアルに出力する。
package main

import (
	"time"

	"github.com/sago35/tinygo-conf-2026-badge/firmware/badge"
)

func input_main() {
	sw1, sw2 := badge.NewButtons()
	joy := badge.NewJoystick()

	for {
		x, y, btn := joy.Read()
		rx, ry := joy.Raw()
		println("SW1:", sw1.Pressed(), "SW2:", sw2.Pressed(),
			"JOY x:", x, "y:", y, "btn:", btn, "raw:", rx, ry)
		time.Sleep(100 * time.Millisecond)
	}
}
