// Code generated by go generate; DO NOT EDIT.
// Source: ../ble-sensor/main.go

// BLE ペリフェラルとして動作し、基板上のセンサーと入出力を公開する。
//
// アドバタイズ名は "TinyGo Conf 2026 #XXXXXX" (XXXXXX はチップ固有の ID)。
// 同じ ID を LCD にも表示するので、複数のバッジが同時に動いていても
// 自分のバッジを見分けられる。スマートフォンの nRF Connect などから
// 接続して確認できる。
//
//	Environmental Sensing (0x181A)
//	  Temperature (0x2A6E)  int16、0.01 度単位、Read/Notify (2 秒ごと)
//	  Humidity    (0x2A6F)  uint16、0.01% 単位、Read/Notify (2 秒ごと)
//	Badge (7a0d0001-2026-4b61-8467-65bad9e00000)
//	  LED    (7a0d0002-...)  Write (応答あり)。6 バイト (LED1 の R G B、LED2 の R G B) で
//	                         WS2812B 2 個の色を個別に、3 バイトなら両方を同じ色にする
//	  Button (7a0d0003-...)  Read/Notify、1 バイト (bit0 SW1、bit1 SW2、bit2 JOY)
//	  Mode   (7a0d0004-...)  Read/Write、1 バイト。0 = 手動 (LED に書いた色)、1 = 自動 (虹色)
//
// BLE が接続されていない間は LED を blink と同じ虹色で自動的に光らせる。
// 接続中は Mode で切り替える (接続直後は手動)。LED に色を書き込むと手動に戻る。
//
//	CGO_CFLAGS_ALLOW=-fno-short-enums tinygo flash --target esp32s3-box-3 --size short ./examples/ble-sensor
//
// -tags bledebug を足すと ATT/HCI の処理をシリアルに出すデバッグビルドになる。
// TinyGo 0.43 より古い場合は firmware/README.md の BLE の手順を参照。
//
// 同じディレクトリの webble.html を Chrome / Edge で開くと、Web Bluetooth で
// 接続して温湿度とボタンの表示、LED の色の変更ができる。webble.html は
// https://conf.tinygo-keeb.org/2026/conf2026badge/ でも公開している。
package main

import (
	"image/color"
	"time"

	"tinygo.org/x/bluetooth"
	"tinygo.org/x/tinyfont"
	"tinygo.org/x/tinyfont/freesans"

	"github.com/sago35/tinygo-conf-2026-badge/firmware/badge"
)

var ble_sensor_adapter = bluetooth.DefaultAdapter

const ble_sensor_namePrefix = "TinyGo Conf 2026 #"

var (
	ble_sensor_serviceUUIDBadge = bluetooth.NewUUID([16]byte{0x7a, 0x0d, 0x00, 0x01, 0x20, 0x26, 0x4b, 0x61, 0x84, 0x67, 0x65, 0xba, 0xd9, 0xe0, 0x00, 0x00})
	ble_sensor_charUUIDLED      = bluetooth.NewUUID([16]byte{0x7a, 0x0d, 0x00, 0x02, 0x20, 0x26, 0x4b, 0x61, 0x84, 0x67, 0x65, 0xba, 0xd9, 0xe0, 0x00, 0x00})
	ble_sensor_charUUIDButton   = bluetooth.NewUUID([16]byte{0x7a, 0x0d, 0x00, 0x03, 0x20, 0x26, 0x4b, 0x61, 0x84, 0x67, 0x65, 0xba, 0xd9, 0xe0, 0x00, 0x00})
	ble_sensor_charUUIDMode     = bluetooth.NewUUID([16]byte{0x7a, 0x0d, 0x00, 0x04, 0x20, 0x26, 0x4b, 0x61, 0x84, 0x67, 0x65, 0xba, 0xd9, 0xe0, 0x00, 0x00})
)

// LED のモード (Mode キャラクタリスティックの値)
const (
	ble_sensor_modeManual = 0 // BLE で書き込んだ色
	ble_sensor_modeAuto   = 1 // 虹色の自動点灯 (blink と同じ)
)

var (
	ble_sensor_tempChar   bluetooth.Characteristic
	ble_sensor_humChar    bluetooth.Characteristic
	ble_sensor_ledChar    bluetooth.Characteristic
	ble_sensor_buttonChar bluetooth.Characteristic
	ble_sensor_modeChar   bluetooth.Characteristic
)

var (
	ble_sensor_black = color.RGBA{0, 0, 0, 255}
	ble_sensor_white = color.RGBA{255, 255, 255, 255}
	ble_sensor_gray  = color.RGBA{160, 160, 160, 255}
	ble_sensor_green = color.RGBA{0, 255, 0, 255}
	ble_sensor_cyan  = color.RGBA{0, 200, 255, 255}
)

// LCD に出す状態。変化したときだけ描き直す。
type ble_sensor_screenState struct {
	connected bool
	peer      string
	sensorOK  bool
	deciTemp  int32
	deciHum   int32
	ledColors [badge.WS2812_COUNT]color.RGBA
	ledAuto   bool // 自動点灯中か (未接続、または Mode が自動)
}

func ble_sensor_main() {
	time.Sleep(2 * time.Second)

	serial := badge.SerialNumber()
	name := ble_sensor_namePrefix + serial
	println("device name:", name)

	display := badge.NewDisplay()
	fb := badge.NewFramebuffer(display)
	leds := badge.NewLEDs()
	leds.SetBrightness(32)
	ledColors := make([]color.RGBA, badge.WS2812_COUNT)
	sw1, sw2 := badge.NewButtons()
	joy := badge.NewJoystick()
	sensor := badge.NewSensor()

	state := ble_sensor_screenState{}
	mode := byte(ble_sensor_modeManual) // 接続中の LED モード。未接続時は常に自動
	dirty := true
	ble_sensor_drawScreen(fb, name, serial, &state)

	println("enabling BLE...")
	ble_sensor_must("enable BLE stack", ble_sensor_adapter.Enable())

	ble_sensor_adapter.SetConnectHandler(func(dev bluetooth.Device, connected bool) {
		if connected {
			println("connected:", dev.Address.String())
			state.peer = dev.Address.String()
		} else {
			println("disconnected:", dev.Address.String())
			state.peer = ""
			mode = ble_sensor_modeManual // 次の接続は手動から
			ble_sensor_modeChar.Write([]byte{ble_sensor_modeManual})
		}
		state.connected = connected
		dirty = true
	})

	ble_sensor_must("add ESS service", ble_sensor_adapter.AddService(&bluetooth.Service{
		UUID: bluetooth.ServiceUUIDEnvironmentalSensing,
		Characteristics: []bluetooth.CharacteristicConfig{
			{
				Handle: &ble_sensor_tempChar,
				UUID:   bluetooth.CharacteristicUUIDTemperature,
				Value:  []byte{0, 0},
				Flags:  bluetooth.CharacteristicReadPermission | bluetooth.CharacteristicNotifyPermission,
			},
			{
				Handle: &ble_sensor_humChar,
				UUID:   bluetooth.CharacteristicUUIDHumidity,
				Value:  []byte{0, 0},
				Flags:  bluetooth.CharacteristicReadPermission | bluetooth.CharacteristicNotifyPermission,
			},
		},
	}))
	ble_sensor_must("add badge service", ble_sensor_adapter.AddService(&bluetooth.Service{
		UUID: ble_sensor_serviceUUIDBadge,
		Characteristics: []bluetooth.CharacteristicConfig{
			{
				Handle: &ble_sensor_ledChar,
				UUID:   ble_sensor_charUUIDLED,
				Value:  make([]byte, 3*badge.WS2812_COUNT),
				// Write Command (応答なし) は HCI バックエンドが処理しないので Write Request のみ
				Flags: bluetooth.CharacteristicReadPermission | bluetooth.CharacteristicWritePermission,
				WriteEvent: func(client bluetooth.Connection, offset int, value []byte) {
					if offset != 0 || len(value) < 3 {
						return
					}
					// 3 バイトごとに LED1, LED2, ... の色。足りない分は最後の色を使う
					for i := range ledColors {
						k := 3 * i
						if k+3 > len(value) {
							k = len(value) - len(value)%3 - 3
						}
						ledColors[i] = color.RGBA{R: value[k], G: value[k+1], B: value[k+2], A: 255}
					}
					for i, c := range ledColors {
						println("LED", i+1, ":", c.R, c.G, c.B)
					}
					leds.WriteColors(ledColors)
					copy(state.ledColors[:], ledColors)
					// 色を書き込まれたら手動に戻す
					if mode != ble_sensor_modeManual {
						mode = ble_sensor_modeManual
						ble_sensor_modeChar.Write([]byte{ble_sensor_modeManual})
					}
					dirty = true
				},
			},
			{
				Handle: &ble_sensor_modeChar,
				UUID:   ble_sensor_charUUIDMode,
				Value:  []byte{ble_sensor_modeManual},
				Flags:  bluetooth.CharacteristicReadPermission | bluetooth.CharacteristicWritePermission,
				WriteEvent: func(client bluetooth.Connection, offset int, value []byte) {
					if offset != 0 || len(value) < 1 {
						return
					}
					if value[0] == ble_sensor_modeAuto {
						mode = ble_sensor_modeAuto
					} else {
						mode = ble_sensor_modeManual
					}
					println("LED mode:", mode)
					dirty = true
				},
			},
			{
				Handle: &ble_sensor_buttonChar,
				UUID:   ble_sensor_charUUIDButton,
				Value:  []byte{0},
				Flags:  bluetooth.CharacteristicReadPermission | bluetooth.CharacteristicNotifyPermission,
			},
		},
	}))

	adv := ble_sensor_adapter.DefaultAdvertisement()
	ble_sensor_must("configure advertisement", adv.Configure(bluetooth.AdvertisementOptions{
		LocalName:    name,
		ServiceUUIDs: []bluetooth.UUID{bluetooth.ServiceUUIDEnvironmentalSensing},
	}))
	ble_sensor_must("start advertisement", adv.Start())
	println("advertising as", name)

	lastSensor := time.Time{}
	prevButtons := byte(0xff)
	hue := 0
	for {
		// 未接続中、または接続中でも Mode が自動なら虹色 (blink と同じ)
		auto := !state.connected || mode == ble_sensor_modeAuto
		if auto {
			hue++
			for i := range ledColors {
				ledColors[i] = ble_sensor_hueColor(uint8(hue*4 + i*128))
			}
			leds.WriteColors(ledColors)
		}
		if auto != state.ledAuto {
			state.ledAuto = auto
			if !auto {
				// 手動に戻るときは BLE で指定された色に戻す
				copy(ledColors, state.ledColors[:])
				leds.WriteColors(ledColors)
			}
			dirty = true
		}

		// ボタン状態は変化したときだけ通知
		var b byte
		if sw1.Pressed() {
			b |= 1 << 0
		}
		if sw2.Pressed() {
			b |= 1 << 1
		}
		if joy.Pressed() {
			b |= 1 << 2
		}
		if b != prevButtons {
			prevButtons = b
			ble_sensor_buttonChar.Write([]byte{b})
		}

		// 温湿度は 2 秒ごとに更新
		if time.Since(lastSensor) > 2*time.Second {
			lastSensor = time.Now()
			if err := sensor.Read(); err == nil {
				state.deciTemp = sensor.DeciCelsius()
				state.deciHum = sensor.DeciRelHumidity()
				state.sensorOK = true
				t := state.deciTemp * 10 // 0.01 度単位
				h := state.deciHum * 10  // 0.01% 単位
				ble_sensor_tempChar.Write([]byte{byte(t), byte(t >> 8)})
				ble_sensor_humChar.Write([]byte{byte(h), byte(h >> 8)})
			} else {
				println("sensor read error:", err.Error())
				state.sensorOK = false
			}
			dirty = true
		}

		if dirty {
			dirty = false
			ble_sensor_drawScreen(fb, name, serial, &state)
		}
		time.Sleep(20 * time.Millisecond)
	}
}

// drawScreen は LCD に名前、ID、BLE の状態、温湿度を描く。
func ble_sensor_drawScreen(fb *badge.Framebuffer, name, serial string, s *ble_sensor_screenState) {
	w, h := fb.Size()
	fb.FillScreen(ble_sensor_black)
	tinyfont.WriteLine(fb, &freesans.Bold12pt7b, 8, 28, "TinyGo Conf 2026", ble_sensor_white)

	// ID は大きく表示
	tinyfont.WriteLine(fb, &freesans.Regular9pt7b, 8, 60, "ID", ble_sensor_gray)
	tinyfont.WriteLine(fb, &freesans.Bold24pt7b, 8, 100, serial, ble_sensor_cyan)

	// BLE の状態
	status := "advertising"
	statusColor := ble_sensor_gray
	if s.connected {
		status = "connected"
		statusColor = ble_sensor_green
	}
	tinyfont.WriteLine(fb, &freesans.Regular9pt7b, 8, 130, "BLE: "+status, statusColor)
	if s.connected && s.peer != "" {
		tinyfont.WriteLine(fb, &freesans.Regular9pt7b, 8, 150, s.peer, ble_sensor_gray)
	}

	// 温湿度
	if s.sensorOK {
		tinyfont.WriteLine(fb, &freesans.Regular12pt7b, 8, 190, ble_sensor_deci(s.deciTemp)+" C   "+ble_sensor_deci(s.deciHum)+" %", ble_sensor_white)
	} else {
		tinyfont.WriteLine(fb, &freesans.Regular9pt7b, 8, 190, "sensor: --", ble_sensor_gray)
	}

	// LED の現在色を右下に表示 (左から LED1, LED2, ...)。自動点灯中は "auto"
	if s.ledAuto {
		tinyfont.WriteLine(fb, &freesans.Regular9pt7b, w-56, h-16, "auto", ble_sensor_gray)
	} else {
		for i, c := range s.ledColors {
			x := w - 8 - int16(len(s.ledColors)-i)*36
			fb.FillRectangle(x, h-40, 32, 32, c)
		}
	}
	tinyfont.WriteLine(fb, &freesans.Regular9pt7b, 8, h-12, "LED", ble_sensor_gray)
	fb.Display()
}

func ble_sensor_must(action string, err error) {
	for err != nil {
		println("failed to " + action + ": " + err.Error())
		time.Sleep(time.Second)
	}
}

// hueColor は 0..255 の色相を RGB に変換する (examples/blink と同じ)。
func ble_sensor_hueColor(h uint8) color.RGBA {
	h3 := uint16(h) * 3
	switch {
	case h3 < 256:
		return color.RGBA{R: 255 - uint8(h3), G: uint8(h3), B: 0, A: 255}
	case h3 < 512:
		h3 -= 256
		return color.RGBA{R: 0, G: 255 - uint8(h3), B: uint8(h3), A: 255}
	default:
		h3 -= 512
		return color.RGBA{R: uint8(h3), G: 0, B: 255 - uint8(h3), A: 255}
	}
}

// deci は 1/10 単位の整数を "12.3" 形式の文字列にする。
func ble_sensor_deci(v int32) string {
	neg := v < 0
	if neg {
		v = -v
	}
	s := ble_sensor_itoa(int(v/10)) + "." + ble_sensor_itoa(int(v%10))
	if neg {
		return "-" + s
	}
	return s
}

func ble_sensor_itoa(v int) string {
	if v == 0 {
		return "0"
	}
	var buf [12]byte
	i := len(buf)
	for v > 0 {
		i--
		buf[i] = byte('0' + v%10)
		v /= 10
	}
	return string(buf[i:])
}
