//go:build ignore

// Run with go generate in this directory. All image decoding happens on the host.
package main

import (
	"bytes"
	"encoding/binary"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"go/types"
	"image"
	_ "image/jpeg"
	_ "image/png"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

var check = flag.Bool("check", false, "check that generated files match their sources")

func main() {
	flag.Parse()
	if err := generate(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate() error {
	dirs, err := os.ReadDir("..")
	if err != nil {
		return err
	}
	wanted := make(map[string]bool)
	var registry bytes.Buffer
	registry.WriteString("// Code generated by go generate; DO NOT EDIT.\n\npackage main\n\nvar programs = [...]program{\n")
	for _, dir := range dirs {
		if !dir.IsDir() || dir.Name() == "all" {
			continue
		}
		paths, err := filepath.Glob(filepath.Join("..", dir.Name(), "*.go"))
		if err != nil {
			return err
		}
		// Host tests are not part of the firmware.
		sources := paths[:0]
		for _, path := range paths {
			if !strings.HasSuffix(path, "_test.go") {
				sources = append(sources, path)
			}
		}
		paths = sources
		if len(paths) == 0 {
			continue
		}
		prefix := strings.ReplaceAll(dir.Name(), "-", "_") + "_"
		fset := token.NewFileSet()
		files := make(map[string]*ast.File)
		for _, path := range paths {
			source, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			source, err = adapt(dir.Name(), filepath.Base(path), source)
			if err != nil {
				return err
			}
			file, err := parser.ParseFile(fset, path, source, parser.ParseComments)
			if err != nil {
				return err
			}
			files[path] = file
		}
		// Resolve references between files without loading target-only packages
		// such as machine. Rename package objects, preserving locals and fields.
		universe := ast.NewScope(nil)
		for _, name := range types.Universe.Names() {
			universe.Insert(ast.NewObj(ast.Bad, name))
		}
		importer := func(_ map[string]*ast.Object, path string) (*ast.Object, error) {
			return ast.NewObj(ast.Pkg, filepath.Base(path)), nil
		}
		pkg, err := ast.NewPackage(fset, files, importer, universe)
		if err != nil {
			return fmt.Errorf("%s: %w", dir.Name(), err)
		}
		if pkg.Scope.Lookup("main") == nil {
			return fmt.Errorf("%s: no main function", dir.Name())
		}
		renames := make(map[*ast.Object]string)
		for name, obj := range pkg.Scope.Objects {
			if name == "init" {
				continue
			}
			if strings.HasPrefix(dir.Name(), "wifi-") && (name == "ssid" || name == "password") {
				continue // Shared -X main.ssid / main.password in the launcher.
			}
			renames[obj] = prefix + name
		}
		for _, path := range paths {
			file := files[path]
			if err := embedAssets(dir.Name(), path, file); err != nil {
				return err
			}
			// The parser leaves bare composite-literal keys unresolved because
			// they may be struct fields. In arrays/maps they are expressions.
			ast.Inspect(file, func(n ast.Node) bool {
				literal, ok := n.(*ast.CompositeLit)
				if !ok {
					return true
				}
				switch literal.Type.(type) {
				case *ast.ArrayType, *ast.MapType:
					for _, element := range literal.Elts {
						if pair, ok := element.(*ast.KeyValueExpr); ok {
							if id, ok := pair.Key.(*ast.Ident); ok && id.Obj == nil {
								id.Obj = pkg.Scope.Lookup(id.Name)
							}
						}
					}
				}
				return true
			})
			if strings.HasPrefix(dir.Name(), "wifi-") {
				removeCredentials(file)
			}
			ast.Inspect(file, func(n ast.Node) bool {
				if id, ok := n.(*ast.Ident); ok {
					if name, ok := renames[id.Obj]; ok {
						id.Name = name
					}
				}
				return true
			})
			var out bytes.Buffer
			fmt.Fprintf(&out, "// Code generated by go generate; DO NOT EDIT.\n// Source: %s\n// Launcher input adaptations are defined in generate.go.\n\n", filepath.ToSlash(path))
			if err := format.Node(&out, fset, file); err != nil {
				return err
			}
			name := "example_" + prefix + filepath.Base(path)
			wanted[name] = true
			if err := output(name, out.Bytes()); err != nil {
				return err
			}
		}
		fmt.Fprintf(&registry, "\t{name: %q, run: %smain, wifi: %t, hint: %q},\n", dir.Name(), prefix, strings.HasPrefix(dir.Name(), "wifi-"), hints[dir.Name()])
	}
	registry.WriteString("}\n")
	formatted, err := format.Source(registry.Bytes())
	if err != nil {
		return err
	}
	if err := output("programs.go", formatted); err != nil {
		return err
	}
	stale, err := filepath.Glob("example_*.go")
	if err != nil {
		return err
	}
	sort.Strings(stale)
	for _, path := range stale {
		if wanted[path] {
			continue
		}
		if *check {
			return fmt.Errorf("stale generated file: %s", path)
		}
		if err := os.Remove(path); err != nil {
			return err
		}
	}
	return generateLogo()
}

var hints = map[string]string{
	"rhythm":        "JOY press: first lane",
	"irlearn":       "JOY press: cursor back",
	"selftest":      "Test joystick LEFT last",
	"slotgame":      "SW1: start / stop in order",
	"wifi-httpget":  "HTTP results: USB serial",
	"wifi-server":   "Server IP: USB serial",
	"wifi-joystick": "Server IP: USB serial",
}

// Keep each example's embedded files under its own directory so assets with
// the same name do not collide. The current examples embed exact file paths.
func embedAssets(example, source string, file *ast.File) error {
	for _, group := range file.Comments {
		for _, comment := range group.List {
			if !strings.HasPrefix(comment.Text, "//go:embed ") {
				continue
			}
			patterns := strings.Fields(strings.TrimPrefix(comment.Text, "//go:embed "))
			for i, pattern := range patterns {
				if !filepath.IsLocal(pattern) || strings.ContainsAny(pattern, "*?[]\"'`") {
					return fmt.Errorf("%s: unsupported embed path %q; use exact relative file paths", source, pattern)
				}
				data, err := os.ReadFile(filepath.Join(filepath.Dir(source), pattern))
				if err != nil {
					return err
				}
				target := filepath.Join("assets", example, pattern)
				if !*check {
					if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
						return err
					}
				}
				if err := output(target, data); err != nil {
					return err
				}
				patterns[i] = filepath.ToSlash(target)
			}
			comment.Text = "//go:embed " + strings.Join(patterns, " ")
		}
	}
	return nil
}

// These are the only changes to the standalone sample behavior. Left is
// reserved for returning to the launcher; the joystick button replaces local left input.
func adapt(example, file string, source []byte) ([]byte, error) {
	if file != "main.go" {
		return source, nil
	}
	replace := func(old, new string) error {
		if bytes.Count(source, []byte(old)) != 1 {
			return fmt.Errorf("%s/%s: adaptation no longer matches %q", example, file, old)
		}
		source = bytes.Replace(source, []byte(old), []byte(new), 1)
		return nil
	}
	var edits [][2]string
	switch example {
	case "rhythm":
		edits = [][2]string{
			{"x, y, _ := g.joy.Read()", "x, y, btn := g.joy.Read()"},
			{"pressed[laneLeft] = tilted(-x, g.held[laneLeft])", "pressed[laneLeft] = btn"},
			{`{"L", "D/U", "R", "2", "1"}`, `{"JOY", "D/U", "R", "2", "1"}`},
			{"return lane == laneLeft || lane == laneUpDown || lane == laneRight", "return lane == laneUpDown || lane == laneRight"},
			{"                ←   ↓か↑   →   SW2  SW1", "              JOY押 ↓か↑   →   SW2  SW1"},
		}
	case "irlearn":
		edits = [][2]string{
			{"prev2      bool", "prev2      bool\n\tprevJoy    bool"},
			{"x, y, _ := s.joy.Read()", "x, y, joyBtn := s.joy.Read()\n\tev.left = joyBtn && !s.prevJoy\n\ts.prevJoy = joyBtn"},
			{"case x < -dirThreshold:\n\t\tdir = 3\n\t", ""},
			{`"left/right: cursor"`, `"JOY/right: cursor"`},
			{"名前入力: 左右でカーソル移動", "名前入力: JOY押し込み/右でカーソル移動"},
		}
	}
	for _, edit := range edits {
		if err := replace(edit[0], edit[1]); err != nil {
			return nil, err
		}
	}
	return source, nil
}

func removeCredentials(file *ast.File) {
	decls := file.Decls[:0]
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if ok && gen.Tok == token.VAR {
			specs := gen.Specs[:0]
			for _, spec := range gen.Specs {
				value := spec.(*ast.ValueSpec)
				if len(value.Names) == 1 && (value.Names[0].Name == "ssid" || value.Names[0].Name == "password") {
					continue
				}
				specs = append(specs, spec)
			}
			gen.Specs = specs
			if len(specs) == 0 {
				continue
			}
		}
		decls = append(decls, decl)
	}
	file.Decls = decls
}

func output(path string, data []byte) error {
	if *check {
		current, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if !bytes.Equal(current, data) {
			return fmt.Errorf("%s is out of date; run go generate ./examples/all", path)
		}
		return nil
	}
	return os.WriteFile(path, data, 0644)
}

func generateLogo() error {
	file, err := os.Open("img/logo.jpg")
	if err != nil {
		return err
	}
	defer file.Close()
	img, _, err := image.Decode(file) // Detect the content, regardless of extension.
	if err != nil {
		return err
	}
	const size = 240
	bounds := img.Bounds()
	w, h := size, size
	if bounds.Dx() > bounds.Dy() {
		h = max(1, bounds.Dy()*size/bounds.Dx())
	} else {
		w = max(1, bounds.Dx()*size/bounds.Dy())
	}
	xoff, yoff := (size-w)/2, (size-h)/2
	raw := make([]byte, size*size*2)
	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			// Box averaging keeps fine logo details at the LCD's resolution.
			x0, y0 := x*bounds.Dx()/w, y*bounds.Dy()/h
			x1, y1 := max(x0+1, (x+1)*bounds.Dx()/w), max(y0+1, (y+1)*bounds.Dy()/h)
			var r, g, b, n uint64
			for sy := y0; sy < y1; sy++ {
				for sx := x0; sx < x1; sx++ {
					cr, cg, cb, _ := img.At(bounds.Min.X+sx, bounds.Min.Y+sy).RGBA()
					r, g, b, n = r+uint64(cr), g+uint64(cg), b+uint64(cb), n+1
				}
			}
			pixel := uint16(r/n>>11)<<11 | uint16(g/n>>10)<<5 | uint16(b/n>>11)
			pos := ((y+yoff)*size + x + xoff) * 2
			binary.BigEndian.PutUint16(raw[pos:], pixel)
		}
	}
	return output("img/logo.rgb565", raw)
}
