// Code generated by go generate; DO NOT EDIT.

package main

var programs = [...]program{
	{name: "aht21b", run: aht21b_main, wifi: false, hint: ""},
	{name: "audio", run: audio_main, wifi: false, hint: ""},
	{name: "audiotest", run: audiotest_main, wifi: false, hint: ""},
	{name: "ble-scanner", run: ble_scanner_main, wifi: false, hint: ""},
	{name: "ble-sensor", run: ble_sensor_main, wifi: false, hint: ""},
	{name: "blink", run: blink_main, wifi: false, hint: ""},
	{name: "demo", run: demo_main, wifi: false, hint: ""},
	{name: "dht20", run: dht20_main, wifi: false, hint: ""},
	{name: "display", run: display_main, wifi: false, hint: ""},
	{name: "i2cscan", run: i2cscan_main, wifi: false, hint: ""},
	{name: "input", run: input_main, wifi: false, hint: ""},
	{name: "ir", run: ir_main, wifi: false, hint: ""},
	{name: "irlearn", run: irlearn_main, wifi: false, hint: "JOY press: cursor back"},
	{name: "joyraw", run: joyraw_main, wifi: false, hint: ""},
	{name: "rhythm", run: rhythm_main, wifi: false, hint: "JOY press: first lane"},
	{name: "selftest", run: selftest_main, wifi: false, hint: "Test joystick LEFT last"},
	{name: "slotgame", run: slotgame_main, wifi: false, hint: "SW1: start / stop in order"},
	{name: "wifi-httpget", run: wifi_httpget_main, wifi: true, hint: "HTTP results: USB serial"},
	{name: "wifi-joystick", run: wifi_joystick_main, wifi: true, hint: "Server IP: USB serial"},
	{name: "wifi-server", run: wifi_server_main, wifi: true, hint: "Server IP: USB serial"},
}
